anchore/grype

- README.md
Signed-off-by: Ross Turk <ross@rossturk.com>
Added a warning banner to the top of the README, right under the features list. At the bottom, there is now a feature wish list.
> Add future ideas + beta warning to README

- README.md
Replaced stray syft entries with grype
Signed-off-by: nlevine@anchore.com
> Replaced stray syft entries with grype

- README.md
Same content, just bullet points instead of a single item for each type. Just visually easier to identify if you're looking for this info.
> Update README.md to highlight supported distros and languages

- go.mod
- go.sum
- grype/presenter/json/presenter_test.go
- grype/presenter/json/test-fixtures/snapshot/TestJsonPresenter.golden
- grype/presenter/json/vulnerability.go
- grype/presenter/table/presenter.go
- grype/presenter/table/presenter_test.go
- grype/presenter/table/test-fixtures/snapshot/TestTablePresenter.golden
- grype/vulnerability/vulnerability.go
Adds "Fixed In" version to the presenters.
Closes #144
> Add fixed-in-version to the presenters

- README.md
- cmd/completion.go
- cmd/root.go
- go.mod
- go.sum
- resources/shell-completion.sh
Add completion script, ValidArgsFunction to root command to list docker images using docker go SDK, and update README
Signed-off-by: Samuel Dacanay <sam.dacanay@anchore.com>
> Shell completion via Cobra utility

- cmd/version.go
- internal/version/build.go
Opening per conversation in https://github.com/anchore/syft/pull/171
Signed-off-by: Samuel Dacanay <sam.dacanay@anchore.com>
> Fix json keys to be camel case instead of kebab

- .bouncer.yaml
- go.mod
- go.sum
- grype/presenter/json/presenter.go
- grype/presenter/json/test-fixtures/snapshot/TestJsonPresenter.golden
- grype/presenter/json/vulnerability.go
- grype/vulnerability/namespace_test.go
Did a simple find/replace to fix the keys, but if any of these are stored as JSON persistently, it will require update there too
Signed-off-by: Samuel Dacanay <sam.dacanay@anchore.com>
> Change kebab case to camelCase

- cmd/root.go
- cmd/root_test.go
Fixes a bad merge from conflicting PRs (replacing results with matches)
> Fix replacement of results with matches

- DEVELOPING.md
- README.md
- Moves the `Developing` section to a separate `DEVELOPING.md` file in the root of the repo.
- Adds a `Getting Started` section to the developing docs.
- Generally updates the `README`
> Update high level docs

- go.mod
- go.sum
> Use latest versions of anchore repos

- go.mod
- go.sum
Pulling in the fix from https://github.com/anchore/syft/pull/183
> Always return a cleanup function from scope

- .github/workflows/release.yaml
- .gitignore
- Makefile
Adds changelog generation automatically into the release process
Closes #165
> Add changelog generation into the release process

- go.mod
- go.sum
Pulls in the upstreams for https://github.com/anchore/syft/pull/192 and https://github.com/anchore/syft/pull/188
> Support file/dir tilde expansion + APK cataloger xattr fix

- go.mod
- go.sum
> Bump go.mod item versions

- .goreleaser.yaml
🔥 🔥 🔥  **WAIT UNTIL v0.1.0 BEFORE MERGING!**
Closes #119 
> Set prerelease to auto

- README.md
Same as https://github.com/anchore/syft/pull/208
> docs: update the readme to remove pre-release note

- go.mod
- go.sum
- grype/matcher/bundler/matcher.go
- grype/matcher/common/cpe_matchers_test.go
- grype/matcher/common/language_matchers_test.go
- grype/presenter/cyclonedx/presenter.go
- grype/presenter/json/document.go
- grype/version/format.go
- grype/version/format_test.go
- test/integration/db_mock_test.go
- test/integration/match_coverage_test.go
- test/integration/test-fixtures/image-debian-match-coverage/ruby/specifications/bundler.gemspec
Pulls in the work from https://github.com/anchore/syft/issues/197 with the gemspec cataloger
> Incorporate gemspec cataloger

- grype/presenter/json/package.go
- grype/presenter/json/presenter_test.go
- grype/presenter/json/test-fixtures/snapshot/TestJsonDirsPresenter.golden
- grype/presenter/json/test-fixtures/snapshot/TestJsonImgsPresenter.golden
> Represent CPEs as formatted strings

- ui/event_handlers.go
> Align status text column with that of Syft handlers

- internal/file/tar_test.go
Follow up to https://github.com/anchore/grype/pull/294#issuecomment-820604208
> Remove tar test testify comment

- README.md
> Include references back to Syft

- test/inline-compare/compare.py
Remove upper limit to alpine-vuln inline-compare testing, this should fix the pipeline failure.
> Fix acceptance tests

- grype/pkg/package_test.go
Follow-up PR to address comments in #230
> Adjust tests for VirtualPath java metadata addition

- README.md
Several features have been added that hadn't yet made it into the README. This PR updates our README to reflect those features.
> Update README with latest capabilities

- README.md
> Add callout for OSS meetup

- .github/scripts/go-mod-tidy-check.sh
- Makefile
- go.sum
Fixes #358 
This PR, once merged, is expected to unblock Grype's release process.
> Catch unclean go.sum files in pipeline

- README.md
> Revert "Add callout for OSS meetup"

- go.mod
- go.sum
Should cull back several false positives for CPE-based results.
> Incorporate CPE generation enhancements

- go.mod
- go.sum
Mainly to pull in https://github.com/anchore/syft/pull/447
> Bump syft to v0.20.0

- README.md
> docs: wrong environment variable: SYFT_

- grype/pkg/syft_json_provider.go
- grype/pkg/syft_json_provider_test.go
- grype/pkg/test-fixtures/syft-spring.json
Improved logging and added a String() method too. 
Also, added a test case for parsing
Partially addressed #354 
Signed-off-by: Samuel Dacanay <sam.dacanay@anchore.com>
> Ensure that virtual path is reported for java archives.

- README.md
> Revert "Add announcement for upcoming OSS meetup"

- internal/logger/logrus.go
> update log file permissions to 0644

- go.mod
- go.sum
This is the final PR needed to close #417
> Update Syft to v0.24.1

- .github/ISSUE_TEMPLATE/config.yml
> Update description for Slack link

- .golangci.yaml
- Makefile
- cmd/db_check.go
- cmd/db_delete.go
- cmd/db_import.go
- cmd/db_status.go
- cmd/db_update.go
- cmd/event_loop.go
- cmd/report_writer.go
- cmd/root.go
- grype/db/curator.go
- grype/db/curator_test.go
- grype/lib.go
- grype/matcher/apk/matcher.go
- grype/presenter/cyclonedx/vulnerability.go
- grype/presenter/models/descriptor.go
- grype/presenter/models/document.go
- internal/config/application.go
- internal/config/database.go
- test/integration/compare_sbom_input_vs_lib_test.go
Follow up from https://github.com/anchore/grype/pull/442#discussion_r722612680 . While I was at it I updated our linter.
> Update linter + fix whitespace

- README.md
> Add private registry authorization section to README

- go.mod
- go.sum
- grype/matcher/rpmdb/matcher_mocks_test.go
- Update grype-db dependency for the distro-feed namespace mapping
- Add test to verify the above mapping
Signed-off-by: Swathi Gangisetty <swathi@anchore.com>
> Support vulnerability matching for Rocky Linux

- README.md
Signed-off-by: Dan Luhring <dan+github@luhrings.com>
> Announce meetup on 2021-12-01

- README.md
Signed-off-by: Dan Luhring <dan+github@luhrings.com>
> Remove webinar announcement

- .github/workflows/release.yaml
Problem introduced from refactor: https://github.com/anchore/grype/pull/512
> Fix release quality gate section

- README.md
Signed-off-by: Dan Luhring <dan+github@luhrings.com>
> Add section for community meetings

- go.mod
- go.sum
- grype/matcher/rpmdb/matcher_mocks_test.go
Necessary changes to provide AlmaLinux OS Support
> Adding AlmaLinux OS Support

- go.mod
- go.sum
Closes #523 (fixed in syft PR https://github.com/anchore/syft/pull/658)
> Bump syft to v0.32.0

- go.mod
- go.sum
> Pull in go binary cataloger panic fix

- go.mod
- go.sum
> bump syft to v0.32.2

- go.mod
- go.sum
Signed-off-by: Alex Goodman <alex.goodman@anchore.com>
> Bump syft to v0.33.0

- grype/presenter/models/source.go
- grype/presenter/models/source_test.go
> Add support for file scheme to presenter model

- README.md
- cmd/root.go
- go.mod
- go.sum
- grype/lib.go
- grype/pkg/provider.go
- grype/pkg/provider_test.go
- grype/pkg/syft_provider.go
- grype/pkg/test-fixtures/image-simple/Dockerfile
- grype/pkg/test-fixtures/image-simple/package.json
- grype/pkg/test-fixtures/image-simple/target/nested/package.json
- grype/version/constraint_unit_test.go
- internal/config/application.go
- test/integration/match_by_image_test.go
- test/integration/utils_test.go
This addresses #389 after the corresponding Syft PR (https://github.com/anchore/syft/pull/695) has been merged
> Add --exclude flag

- cmd/cmd.go
- grype/lib.go
> Grype verbose log version 

- go.mod
- go.sum
- grype/matcher/apk/matcher_test.go
- grype/matcher/common/cpe_matchers_test.go
- grype/pkg/syft_provider.go
- test/integration/match_by_image_test.go
- test/integration/utils_test.go
> update syft version for new release

- go.mod
- go.sum
upgrade stereoscope to resolve https://github.com/containerd/containerd/security/advisories/GHSA-mvff-h3cj-wj9c
Related PR:
https://github.com/anchore/syft/pull/741
https://github.com/anchore/stereoscope/pull/95
> upgrade stereoscope

- go.mod
- go.sum
> update to secure syft version

- .goreleaser.yaml
> remove goreleaser replacements and update checksum removals

- Dockerfile
> convert from deprecated org.label-schema to OCI Annotations

- Makefile
Signed-off-by: Vijay Pillai <vijay.pillai@anchore.com>
> Update go-bouncer to v0.3.0

- README.md
Signed-off-by: Daniel Nurmi <nurmi@anchore.com>
> Add list of public data feeds that are sourced when populating grype's vulnerability database

- go.mod
- go.sum
Signed-off-by: Jonas Galvão Xavier <jonas.agx@gmail.com>
> update stereoscope version to include Podman

- .goreleaser.yaml
> remove duplicate manifest

- .github/scripts/apple-signing/cleanup.sh
- .github/scripts/apple-signing/setup-dev.sh
- .github/scripts/apple-signing/setup-import-cert.sh
- .github/scripts/apple-signing/setup-prod.sh
- .github/scripts/apple-signing/setup.sh
- .github/scripts/apple-signing/sign.sh
Similar PR to https://github.com/anchore/syft/pull/851 
Only change not made: verifying signing functionality in CI on PR changes (thus, no goreleaser config changes)
> Share import mac code signing certificate steps for release

- README.md
We'd like to add an announcement for Anchore's upcoming meetup on March 23rd. We'll plan to leave it up until after the meetup's concluded on the 23rd.
> Add announcement for Anchore OSS Meetup

- .github/scripts/apple-signing/notarize.sh
`brew install gon` seems to be failing.
> Directly install gon

- go.mod
- go.sum
> Update Syft to v0.41.6

- grype/db/v3/namespace_test.go
- grype/matcher/rpmdb/matcher_test.go
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
> Misc typo fixes

- README.md
- cmd/root.go
Signed-off-by: Jonas Galvão Xavier <jonas.agx@gmail.com>
> add podman to readme and examples

- README.md
Proposing changes to remove our 3/23 meetup
> Remove announcement for OSS Meetup

- grype/presenter/config.go
- grype/presenter/config_test.go
- grype/presenter/template/test-fixtures/test.valid.template
* Check if template file exists
* Check if template file is readable
* Check if template file is parsable using text\template
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
> template: Check sanity for template file

- go.mod
- go.sum
- grype/pkg/package_test.go
- test/integration/compare_sbom_input_vs_lib_test.go
- test/integration/test-fixtures/image-arch-match-coverage/Dockerfile
> update grype to latest syft patch v0.48.1

- README.md
> remove OSS Meetup message

- go.mod
- go.sum
> update syft => v0.49.0

- README.md
Added an example of running grype using the Docker container method
> Added Docker example to Readme

- go.mod
- go.sum
- grype/db/v3/namespace_test.go
- grype/pkg/package_test.go
- test/integration/compare_sbom_input_vs_lib_test.go
> update syft to v0.50.0

- grype/version/semantic_version.go
> fix typo in log message

- .github/scripts/apple-signing/setup-prod.sh
- .github/workflows/release.yaml
> add env variables and keychain for GHCR publish

- Makefile
> bump bouncer to v0.4.0

- .github/workflows/release.yaml
> push older version for mac runner stability

- .github/workflows/release.yaml
> revert to old docker action

- .github/workflows/release.yaml
> macos-latest for signing

- .github/scripts/apple-signing/setup-prod.sh
> remove env variable dependencies and keychain from signing script

- Makefile
> update syft version location for Makefile

- Makefile
- cmd/db_check.go
- cmd/db_update.go
- grype/db/curator.go
Signed-off-by: Michael de Senna <desenna@gmail.com>
Closes https://github.com/anchore/grype/issues/754
> feat: enrich db check cmd feedback

- grype/db/listing_test.go
Signed-off-by: Michael de Senna <desenna@gmail.com>
> test: rm mustConst since unused

- README.md
Added the newly available environment variables used to change the data staleness to the README.
Signed-off-by: Brock Renninger <brock@renninger.dev>
> Update README.md to include updated environment variables

- .github/workflows/update-bootstrap-tools.yml
- Makefile
> workflow to create automated PRs to update bootstrap tools

- .github/workflows/update-bootstrap-tools.yml
> fix getting latest gosimports version

- .github/workflows/validations.yaml
- .goreleaser_docker.yaml
- Makefile
Additionally restores docker builds to be in PR validations
> Fix docker build typo

- README.md
Missed a spot in #910, my apologies for the PR spam!
> docs: add Singularity to "features" in README

- .github/workflows/release.yaml
> grype release message update

- .github/workflows/scorecards.yml
- README.md
Closes #926 
Hi, here is the PR with the changes to enable the OpenSSF Scorecard Gihub Action as described at #926 
Thanks for the attention and any doubts or concerns please reach me out.
> Enable the Scorecard Github Action and badge

- .github/workflows/codeql-analysis.yml
See: https://github.com/anchore/grype/security/code-scanning/89
> chore: code-ql top level read check

- go.mod
- go.sum
- grype/pkg/package_test.go
> chore: bump syft version v0.62.0

- .github/workflows/release.yaml
See #1001 for information on the path forward for releasing syft/grype
> scoped: token release for content write on image assets

- .github/workflows/release.yaml
> chore: update default packages to read

- test/quality/.yardstick.yaml
> chore: update quality gate with latest label data

- test/quality/requirements.txt
> chore: bump yardstick to latest commit

- test/quality/.yardstick.yaml
> chore: add GitLab Community Edition image to quality gate

- internal/file/hasher_test.go
Signed-off-by: Benji Visser <benji@093b.org>
> Add internal/file/hasher test cases

- artifacthub-repo.yml
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
cc: @wagoodman
> chore: claim artifacthub package ownership from developer-guy

- .github/workflows/update-bootstrap-tools.yml
- Makefile
This PR adjusts some things in the `Makefile` to be more like Syft's Makefile and updates the bootstrap update script similarly.
> chore: align makefile and bootstrap tools scripts more with syft

- test/quality/.yardstick.yaml
> chore: update grype quality gate

- test/quality/.yardstick.yaml
> chore: add new images to quality gate

- grype/match/explicit_ignores.go
> fix: ignore some false-positives for ruby gems

- test/quality/.yardstick.yaml
> chore: bump quality gate

- go.mod
- go.sum
- grype/db/curator.go
- grype/db/v3/store/diff.go
- grype/db/v3/store/store.go
- grype/db/v4/store/diff.go
- grype/db/v4/store/store.go
- grype/db/v5/store/diff.go
- grype/db/v5/store/store.go
- grype/differ/differ.go
- grype/matcher/matchers.go
- internal/file/getter.go
This PR updates progress monitor handling based on recent changes to Syft.
> chore: update progress monitor handling

- .github/workflows/release.yaml
- .github/workflows/update-bootstrap-tools.yml
- .github/workflows/update-syft-release.yml
This PR just updates a couple things with workflows:
* use conventional commit messages for automated PRs
* output a correct link to a release in the Slack message
> chore: tweak some workflow text

- grype/db/v3/namespace_test.go
- grype/db/v4/namespace/index_test.go
- grype/db/v5/namespace/index_test.go
- grype/distro/distro.go
- grype/distro/distro_test.go
- grype/distro/test-fixtures/os/chainguard/etc/os-release
- grype/distro/type.go
Related to https://github.com/anchore/vunnel/pull/132
> Implement support for Chainguard Linux

- README.md
> docs: add config flag to configuration section (#1271)

- README.md
- grype/presenter/template/presenter.go
- grype/presenter/template/presenter_test.go
- grype/presenter/template/test-fixtures/snapshot/TestPresenter_Present.golden
- grype/presenter/template/test-fixtures/test.template
> feat: add non-hermetic sprig functions (#1243)

- templates/junit.tmpl
Added JUnit XML template:
https://github.com/anchore/grype/issues/1316
> Add a simple JUnit XML template

- go.mod
- go.sum
- test/integration/match_by_image_test.go
Incorporate https://github.com/anchore/syft/pull/2220
> Incorporate Syft java detection improvements

- grype/db/v3/namespace.go
> chore: fix function name in comment

- grype/db/metadata.go
- grype/db/metadata_test.go
- grype/db/test-fixtures/metadata-edt-timezone/metadata.json
- grype/db/test-fixtures/metadata-gocase/metadata.json
modifying metadata to store provider last successful run date
> feat: modify metadata structure for providers' pull date

- README.md
Does what it says on the tin.
Thanks for making this project!
> Add some more examples for the `config.yaml` file in the README.

- grype/db/metadata.go
- grype/db/metadata_test.go
- grype/db/test-fixtures/metadata-edt-timezone/metadata.json
- grype/db/test-fixtures/metadata-gocase/metadata.json
> Revert "feat: Add providers' pull date to DB metadata structure"

- .github/ISSUE_TEMPLATE/bug_report.md
We sometimes get issues that are difficult to reproduce because we don't know what we scanned. This will hopefully help with that a bit.
1. Should we split false positive and false negative into their own issue type?
2. Is this too wordy? Missing details?
> chore: request artifact in issue template

- cmd/grype/cli/commands/listing_test.go
- cmd/grype/cli/options/database.go
- grype/db/curator.go
- internal/file/getter.go
- internal/file/getter_test.go
This PR adds the User-Agent containing the grype version to the database network operations.
> chore: add grype version to db network operations

- cmd/grype/cli/commands/root.go
> chore: include file specifier in help

- grype/db/legacy/distribution/curator.go
Follow up to #2148 where we should only be creating a last-update-timestamp file when the update check explicitly passes. This also pops the limit for static analysis for this function, but I've elected to defer that refactor for a couple of reasons: I've already refactored this for the v6 curator and this particular issue is functionally more important to fix before another grype release. I've added `changelog-ignore` since it's a bug introduced before any release was done.
> Explicitly skip update ts on check failure

- grype/matcher/rpm/matcher.go
- grype/matcher/rpm/matcher_test.go
> Use epoch from metadata when missing from version string

- grype/version/rpm_constraint_test.go
- grype/version/rpm_version.go
> Account for implicit 0s in rpm release versions

- grype/db/v5/namespace/index.go
- grype/db/v5/namespace/index_test.go
Fixes #2222 
Today when specifying `--distro` you need to provide exactly the correct version information. This is not great since some distros track based on `major` version only and others with `major.minor`. This PR changes this behavior by searching for the closest matching namespace based on the provided distro information. So if the user provides `--distro alpine:3.20` then we'll correctly line this up with the `alpine:3.20` namespace (where as today this will match against `edge`).
This same loosening of namespace searching based on arbitrary version info has been applied to all distros/namespaces within the v5 schema only.
> Search for distro namespaces with incomplete information

- cmd/grype/cli/commands/root.go
- cmd/grype/cli/options/grype.go
- grype/presenter/json/presenter.go
- grype/presenter/json/presenter_test.go
- grype/presenter/models/presenter_bundle.go
- internal/format/presenter.go
- test/cli/cmd_test.go
according to this discussion - https://anchorecommunity.discourse.group/t/grype-scans-in-batches-large-sboms/293/11
we have found out that the pretty mode makes the final json very large, we want to reduce the size by default to avoid OOM.
> add pretty format

- grype/match/explicit_ignores.go
> fix: add explicit igore for problematic CVE-2023-45853

- cmd/grype/cli/commands/db_list.go
- cmd/grype/cli/commands/db_list_test.go
DB list is not filling out assumed values when printing the latest.json URL and DB URL. This PR adjusts the output (diff shown between old and new values):
```diff
*** bad    Thu Mar 20 16:21:34 2025
--- good   Thu Mar 20 16:21:52 2025
***************
*** 1,6 ****
Status:   active
Schema:   v6.0.2
Built:    2025-03-20T04:07:28Z
! Listing:  https://grype.anchore.io/databases
! DB URL:   https://grype.anchore.io/vulnerability-db_v6.0.2_2025-03-20T01:30:59Z_1742443648.tar.zst
Checksum: sha256:d668b9a4bdc4ca4a116452501ee915c669811bc9cc4f0baa3c4ac67a50cf5ca0
--- 1,6 ----
Status:   active
Schema:   v6.0.2
Built:    2025-03-20T04:07:28Z
! Listing:  https://grype.anchore.io/databases/v6/latest.json
! DB URL:   https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-03-20T01:30:59Z_17424 …
```
> `db list` should render out full URLs for text format

- grype/presenter/sarif/presenter.go
- grype/presenter/sarif/presenter_test.go
- grype/presenter/sarif/test-fixtures/snapshot/TestSarifPresenter_directory.golden
- grype/presenter/sarif/test-fixtures/snapshot/TestSarifPresenter_image.golden
Fixes https://github.com/anchore/grype/issues/2511
> feat: add sarif result level

- cmd/grype/cli/commands/root.go
- grype/db/v6/installation/curator.go
This PR just adds a few basic log messages with timing information.
> chore: add some timing info

- cmd/grype/cli/commands/root.go
- grype/pkg/purl_provider.go
- grype/pkg/purl_provider_test.go
> Derive OS distribution from purl

- templates/html.tmpl
I recently had to update the html template to be more responsive (we display it in a pipeline results iframe and size became an issue). While fixing that, I ended up giving the whole interface a bit of a facelift - added some modern touches, made it more user-friendly, and threw in dark mode for good measure. 
The full list of changes is in the summary below, but the main thing is that it should work much better in those pipeline iframes now while also being generally nicer to use.
----
1. **Dark Mode Support & Styling:**
* Support for system dark mode preference was implemented.
* General styling improvements were applied for a cleaner look and feel in both light and dark modes.
* **Enhanced Search Experience:** The search input now features a modern, floating label design.
2. **Data …
> feat(template): improve html template

- README.md
Updated OS name in README based on the name change: https://en.wikipedia.org/wiki/Azure_Linux
> Updated Readme (CBL-Mariner is now Azure Linux)

- grype/db/v5/distribution/curator_test.go
- grype/db/v6/installation/curator_test.go
- grype/matcher/internal/only_vulnerable_targets.go
- grype/matcher/internal/only_vulnerable_versions.go
- grype/pkg/syft_sbom_provider_test.go
- grype/vex/openvex/implementation.go
fix some minor issues in comments
> chore: fix some minor issues in comments

- cmd/grype/cli/commands/root.go
Adds DB info after the load to the log statements as well as package count gathered:
```
[0000] DEBUG gathering packages
[0000]  INFO gathered packages packages=1 time=1.572ms
[0000] DEBUG loading DB
[0000]  INFO loaded DB status=valid time=27.941667ms
[0000] DEBUG ├── schema=v6.0.3
[0000] DEBUG ├── built=2025-06-24T18:25:09Z
[0000] DEBUG ├── from=manual import
[0000] DEBUG └── path=/Users/wagoodman/Library/Caches/grype/db/6/vulnerability.db
```
> chore: Add more detail around cataloging and DB load log statements

- grype/presenter/models/source.go
- grype/presenter/models/source_test.go
This PR adds support for snap sources.
Fixes #2819
> fix: add snap source support

- llms.txt
This PR adds a small text file `llms.txt` to the root of the repo. The goal being to improve responses from generative AI queries, when they're asked about topics pertinent to the contents of this repo.
> doc: Add llms.txt for the 🤖 🕷️
