anchore/grype

.github/scripts/update-version-file.sh, .github/workflows/acceptance-test.yaml, .github/workflows/release.yaml, Makefile
Since we will be cutting betas for a while longer, we want to let users know when there is another beta available. However, after v0.1.0 release, we will not be creating betas that often, but when we do we do not want to let users know there is another version available if the new version is a pre-release (e.g. `v#.#.#-<prerelease>`).
This PR switches the source of truth for when to notify users from the semver on the git tag to using the github releases "prerelease" indicator.
=> Disable prerelease version update check

README.md
Just realized that we don't emphasize the installation instructions anywhere, and a new user would have to scroll down to find the section. Adding a little bit of emphasis as early as possible, as well as in the "Getting Started" sections should help.
=> docs: emphasize installation methods before features and getting started

.github/ISSUE_TEMPLATE/config.yaml
This will add slack channel links as options in the issue template selection box.
=> Add slack links to issue selection

grype/version/constraint.go, grype/version/format.go, grype/version/fuzzy_constraint.go, grype/version/fuzzy_constraint_test.go, grype/version/version.go, test/integration/db_mock_test.go, test/integration/match_coverage_test.go
Closes #91 
By using the `PythonFormat`, the code can explicitly deal with the rules and constraints of PEP440 - luckily getting addressed by the Fuzzy implementation.
Requires https://github.com/anchore/grype-db-builder/pull/53
=> Explicitly use PythonFormat to address PEP440 rules

go.mod, go.sum, grype/matcher/python/matcher.go, test/integration/match_coverage_test.go
I thought this would take much more changes, but it looks like all that is needed is to add the new package type.
Blocked until https://github.com/anchore/syft/pull/150 is merged - this PR will need to update the dependencies to use the new changes.
```text
$ go run main.go -vv  dir://../devml
[...]
[0001] DEBUG searching for vulnerability matches for pkg=Pkg(type=python-setup, name=click, version=1.1.1)
[0001] DEBUG found 1 vulnerabilities for pkg=Pkg(type=python-setup, name=click, version=1.1.1)
[0001] DEBUG   └── vuln='CVE-2015-8768' type='Fuzzy Match' key='cpe[cpe:2.3:*:*:click:1.1.1:*:*:*:*:python:*:*] constraint[none (unknown)]' foundBy='python-matcher')
[0001] DEBUG searching for vulnerability matches for pkg=Pkg(type=egg, name=devml, version=0.5.1)
```
=> Match on `setup.py` files

cmd/version.go, internal/version/build.go
This PR removes the verbose cmd and adds a machine readable format:
```
$ grype version
Application:          grype
Version:              0.1.0-beta.6
BuildDate:            2020-08-10T23:01:19Z
GitCommit:            cbd60606522186b88e345231c0699cedb53266de
GitTreeState:         clean
Platform:             linux/amd64
GoVersion:            go1.14.6
Compiler:             gc
Supported DB Schema:  1
```
```
$ grype version -o json
{
"application: "grype",
"version: "0.1.0-beta.6",
"build-date: "2020-08-10T23:01:19Z",
"git-commit: "cbd60606522186b88e345231c0699cedb53266de",
"git-tree-state: "clean",
"platform: "linux/amd64",
"go-version: "go1.14.6",
"compiler: "gc",
"supported-db-schema":  1
}
```
=> simplify version cmd + add json option

grype/match/match.go, grype/matcher/common/cpe_matchers.go, grype/matcher/common/cpe_matchers_test.go, grype/matcher/common/distro_matchers.go, grype/matcher/common/language_matchers.go, grype/presenter/json/presenter.go, grype/presenter/json/presenter_test.go, grype/presenter/json/test-fixtures/snapshot/TestJsonPresenter.golden, test/integration/match_coverage_test.go
Closes #94 
This PR addresses a problem with CPE matching, where previously (exact) matches were not accounted for, allowing for duplicates to get in.
Additionally, it expands the information on what exactly was matched (via `SearchMatches`), and simplifies the `SearchKey` to include only what was searched on (vs. a string built on the fly).
=> Prevent duplicates, expand on matching information

go.sum, grype/match/match.go, grype/matcher/common/cpe_matchers.go, grype/matcher/common/distro_matchers.go, grype/matcher/common/language_matchers.go, grype/presenter/cyclonedx/presenter_dirs_test.go, grype/presenter/cyclonedx/presenter_imgs_test.go, grype/presenter/json/presenter.go, grype/presenter/json/presenter_test.go, grype/presenter/json/test-fixtures/snapshot/TestJsonPresenter.golden, grype/presenter/table/presenter_test.go, test/integration/match_coverage_test.go
This is a follow up on https://github.com/anchore/grype/pull/137#discussion_r474756009 ; Today the `SearchKey` for a grype Match is an arbitrary string. To allow for more programmatic usefulness of the field, changing the key to a map of items that are used in the search is more useful (as no string parsing is required to interpret the key).
Closes #145
=> Change search key json output to a map

cmd/db_check.go, cmd/db_delete.go, cmd/db_import.go, cmd/db_status.go, cmd/db_update.go
Fixes a crash when no archive is given for db import and additionally is more explicit about positional arguments on remaining db commands.
=> Add positional argument validation for DB commands

cmd/root.go, grype/cpe/cpe.go, grype/lib.go, grype/match/matches.go, grype/matcher/controller.go, grype/presenter/cyclonedx/document.go, grype/presenter/cyclonedx/presenter.go, grype/presenter/cyclonedx/presenter_dirs_test.go, grype/presenter/cyclonedx/presenter_imgs_test.go, grype/presenter/json/presenter.go, grype/presenter/json/presenter_test.go, grype/presenter/presenter.go, grype/presenter/table/presenter.go, grype/presenter/table/presenter_test.go, test/integration/corner_cases_test.go, test/integration/db_mock_test.go, test/integration/match_coverage_test.go
Polishing before release --the "Results" object was never meant to be the final name. This PR finalizes a couple of the TODOs by renaming `Result` -> `Matches` and migrating to the `match` package.
=> Rename Result object to Matches

Makefile, cmd/root.go, cmd/root_test.go, grype/grypeerr/errors.go, grype/grypeerr/expected_error.go, grype/vulnerability/severity.go, internal/config/config.go, internal/ui/etui/ephemeral_tui.go, internal/ui/logger_output.go
Adds the following functionalities:
- the ability to comb through the discovered vulnerabilities and set a non-0 exit code when a vulnerability at or above the given user threshold is found (provided by `--fail-on`).
- a `ExpectedErr` struct for creating errors that are known to be produced from grype. There is room to expand this in the future.
Note: the drop in coverage is somewhat fictitious since a test was added in a package that has no existing tests. 
Closes #129
=> add --fail-on threshold support

go.mod, go.sum
Fixes the currently broken main branch that has go-testutils commits from https://github.com/anchore/grype/pull/154 that had not merged into `main`. 
Those unmerged commits were proposed here: https://github.com/anchore/grype/pull/154
The updates in this PR aren't new, they are just pointing to the same commits as they appear in `main`
=> update go.mod and go.sum

go.sum, grype/presenter/table/presenter.go, grype/presenter/table/presenter_test.go
Prevents the summary table from showing duplicate rows.
Closes #128
=> Remove duplicate rows from the summary table

.github/workflows/static-unit-integration.yaml
Today we are triggering the static analysis and test workflow from push events, which forks for members of the repo, but not for PRs from a fork. This PR adds the `pull_request` trigger to the static analysis and test workflow. Note: this will cause what appears to be duplicate checks for PRs originating from members of the repo, which happens on simultaneous push and PR events. This is somewhat undesirable behavior but the refs being checked are technically different --one running against the typical git `ref` while the other is running against `refs/pull/<prnum>/merge`, as seen from the `GITHUB_REF`.
=> Run checks on PRs from forks

.github/scripts/mac-prepare-for-signing.sh, .github/scripts/mac-sign-and-notarize.sh, .github/scripts/update-version-file.sh, .github/workflows/acceptance-test.yaml, .github/workflows/release.yaml, .goreleaser.yaml, Makefile, gon.hcl
- Adds signing and notarization to the release process to replace the Darwin `.tar.gz` asset with a `.dmg` asset
- Moves several pipeline steps from a Linux runner to a macOS runner and adapts the pipeline logic accordingly
- Makes minor improvements and adds clarifying comments to various release-related files
This implements https://github.com/anchore/project-toolbox/issues/27 for _grype_.
=> Resolve security warning for macOS users

.github/workflows/acceptance-test.yaml, go.mod, go.sum, grype/vulnerability/namespace.go
- Fixes an issue in the acceptance test workflow by adding a missing "bootstrap" step
- Adds Slack notifications for acceptance test failures
- Updates Syft from v0.4.0 to v0.5.1
=> Syft version bump, and improvements to acceptance workflows

.goreleaser.yaml
This is a super small follow-up to https://github.com/anchore/grype/pull/194. I left one line in by mistake... a darwin target in the first build entry within `goreleaser.yaml`.
**Note:** This does **not** warrant an immediate release, since I was able to manually remove the darwin `.tar.gz` from the asset list for v0.3.0.
=> Remove darwin target from primary build entry

.github/scripts/mac-sign-and-notarize.sh, .goreleaser.yaml, Makefile, gon.hcl, install.sh
- Adds "zip" as a `gon` output
- Ensures that ZIP file is a goreleaser artifact and is thus included in the GitHub release assets as well as used for the homebrew installation path
- Removes the "flash" of a Finder window during the execution of `install.sh`
This is also intended to address #203, in that homebrew will now use the `.zip` file (which has been correctly signed and notarized to the standards of macOS) rather than the `.tar.gz` file (which doesn't support notarization).
=> Add signed and notarized ZIP release asset

go.mod, go.sum, grype/logger/logger.go, grype/matcher/apk/matcher_test.go, grype/matcher/common/distro_matchers_test.go, grype/matcher/dpkg/matcher_test.go, grype/matcher/rpmdb/matcher_test.go, grype/presenter/json/test-fixtures/snapshot/TestJsonDirsPresenter.golden, grype/presenter/json/test-fixtures/snapshot/TestJsonImgsPresenter.golden, grype/vulnerability/namespace_test.go, grype/vulnerability/store_adapter_test.go, internal/log/log.go, internal/log/nop.go, internal/logger/logrus.go, test/integration/match_coverage_test.go
- Adds warn log level (in parity with syft)
- Bumps syft to v0.7.1
=> Bump syft from v0.5.1 to v0.7.1

cmd/root.go, go.mod, go.sum, grype/lib.go, grype/presenter/cyclonedx/document.go, grype/presenter/cyclonedx/presenter.go, grype/presenter/cyclonedx/presenter_test.go, grype/presenter/cyclonedx/test-fixtures/snapshot/TestCycloneDxPresenter_CycloneDX_Directory_Presenter.golden, grype/presenter/cyclonedx/test-fixtures/snapshot/TestCycloneDxPresenter_CycloneDX_Image_Presenter.golden, grype/presenter/cyclonedx/vuln-extension.go, grype/presenter/json/descriptor.go, grype/presenter/json/document.go, grype/presenter/json/presenter.go, grype/presenter/json/presenter_test.go, grype/presenter/json/test-fixtures/snapshot/TestEmptyJsonPresenter.golden, grype/presenter/json/test-fixtures/snapshot/TestJsonDirsPresenter.golden, grype/presenter/json/test-fixtures/snapshot/TestJsonImgsPresenter.golden, grype/presenter/presenter.go, grype/vulnerability/namespace_test.go, internal/config/config.go, internal/input.go, internal/ui/select.go, test/integration/corner_cases_test.go, test/integration/match_coverage_test.go
- Adds a new `sbom:` scheme where a user can specify a syft json document as input, skipping the need to parse and catalog an image.
- Adds ability to pipe SBOM json document contents into grype via stdin.
- Incorporates changes from https://github.com/anchore/syft/pull/266
Closes #196
=> Add JSON document import

cmd/completion.go
I've removed the `powershell` completion command because it is not supported.
=> Remove powershell description from completion command

go.mod, go.sum, grype/presenter/json/test-fixtures/snapshot/TestJsonDirsPresenter.golden, grype/presenter/json/test-fixtures/snapshot/TestJsonImgsPresenter.golden
Updates the syft version from **0.8.1** to **0.9.1**.
This also closes https://github.com/anchore/grype/issues/209.
=> Update syft from 0.8.1 to 0.9.2

go.mod, grype/vulnerability/namespace.go, grype/vulnerability/namespace_test.go
The RedHat, CentOS, AmazonLinux, and OracleLinux distros should be using a namespace with explicitly only the major version. Today there are cases where we also use the minor version if the raw data surfaces it (e.g. `rhel:8.3` should really be `rhel:8`). This PR fixes this behavior.
Additionally this corrects the mapping for fedora, which should map to `rhel` as well. A future PR will additionally fix the version mapping for this case (captured in https://github.com/anchore/grype/issues/223).
Closes #221
=> Fix distroNamespace mapping to only use major version for select distros

go.mod, go.sum, grype/version/constraint_expression.go, grype/version/constraint_expression_test.go, grype/version/constraint_unit.go, grype/version/constraint_unit_test.go, internal/parse.go
The existing constraint expression parsing assumed that splitting an expression by `||` is good enough to split OR'd expressions, however versions may have these delimiters within quoted text --the same goes for parenthetical statements. This PR rectifies fortifies the existing parser and allows for quoted versions to have arbitrary characters.
=> Refactor constraint expression parser to allow for quoted versions

.github/workflows/static-unit-integration.yaml, Makefile, go.mod, grype/pkg/provider.go, grype/pkg/provider_test.go, grype/pkg/syft_json_provider.go, grype/pkg/syft_provider.go, test/cli/sbom_input_test.go, test/cli/test-fixtures/sbom-ubuntu-20.04--pruned.json
This PR:
- fixes #235
- decomposes Syft provider logic into discrete tasks
This PR also adds the beginnings of "CLI-level" tests — to ensure that the built binary behaves correctly from a CLI context, such as the handling of data piped to the command's STDIN.
What's done so far:
- introduced a new "cli" make target to run these tests
- introduces tests to cover the cases listed in #235 (with the exception of `~` home directory processing)
- target snapshot builds for CLI tests
- included these tests in the CI pipeline
What's left for consideration:
- factoring out generalized CLI test helpers to a new directory or project
=> Fix intake of SBOM from JSON

grype/version/constraint_expression.go
The `text/scanner` is used for constraint expression tokenization. If no error handler is provided to the scanner then errors are reported to stdout by default. This PR adds a handler which ignores all scanner tokenization errors, which is safe under the current context (see the added comments for details). 
Closes #241
=> Suppress version constraint token scanner errors

grype/presenter/json/test-fixtures/image-simple/Dockerfile
The json presenter Dockerfile had been missing for some time now --once #257 was merged it became apparent that this fixture was not committed. This implies that we additionally have a cache + fixture image name collision that needs to be adjusted in the way fixture images are built in stereoscope (future PR). This PR only restores the fixture.
=> Re-adding json presenter fixture

.github/workflows/acceptance-test.yaml
Now that docker is required for snapshot builds it is more convenient to build on a linux box.
=> Move snapshot builds to linux

.github/workflows/release.yaml
The https://github.com/docker/login-action github action is not supported on mac, thus we need to login manually (see https://github.com/anchore/grype/runs/2179331427?check_suite_focus=true)
=> Manually login to docker via cli during release

.github/workflows/release.yaml, Makefile
Currently the release step logs into docker, however, this needs to occur after creating the keychain used for mac signing.
=> Move docker login after keychain creation

.github/workflows/release.yaml, Makefile
- Now that docker is rate limiting anonymous pulls, it is useful to be authenticated against docker.io for steps that require docker pull
- Noticed the bootstrap cache step referenced the wrong step name, fixed
- Noticed the release title referenced "snapshot" artifacts, fixed
=> Ensure docker is auth'd during entire release process

grype/db/curator.go, grype/db/curator_test.go, internal/config/config.go
This PR stages the DB into a subdirectory named by the schema version. This will help with users that run multiple versions of grype -- the DBs for each incompatible version of grype will reside in separate directories.
Closes #271
=> Stage DB file within directory named by schema version

go.mod, go.sum
This PR pulls in the fixes from https://github.com/anchore/stereoscope/pull/63 and https://github.com/anchore/syft/pull/368.
Summary of fix in stereoscope: today when setting docker pull options we are responsible for base64 encoding the RegistryAuth JSON, which is an object containing username and password. Before base64 encoding we are not making certain that the JSON marshaling will not escape specific characters typical to HTML documents. This PR swaps out the JSON unmarshal with a JSON encoder with HTML escaping turned off.
Closes #254
=> Ensure credentials are not HTML encoded

internal/config/registry.go, internal/config/registry_test.go
Enforces that user and password OR a token must be present --no partial values allowed now. (Follow up to https://github.com/anchore/grype/pull/290#discussion_r613207047)
=> Modify registry credential verification

.github/workflows/release.yaml
Currently the quality gate has the Go version number encoded into the check names (something that will be removed in the future). In the meantime, this PR fixes the check names to match a previous PR that bumped the Go version.
=> Fix release pipeline quality gate

Makefile
The release pipeline downloads the required go modules, however, this may modify the go.sum. The state of the sum may be equivalent to that of what is checked into git, however, to ensure this is the case `go mod tidy` must be run to get the reduced state. If the state differs, then there is a problem and the release should be halted (goreleaser does this), otherwise it is safe to continue.
```
❯ go clean --modcache
❯ git status
On branch bootstrap-go-mod-tidy
nothing to commit, working tree clean
❯ go mod download
❯ git status
On branch bootstrap-go-mod-tidy
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   go.sum
no changes added to commit (use "git add" and/or "git …
```
=> Ensure consistent go.sum state during release

Makefile, internal/file/tar.go, internal/file/tar_test.go
We should not trust values derived from tar headers when crafting file paths. This adjusts the tar processing for DB import / update to consider this and error out when this case is found.
=> Safely join paths derived from tar headers

README.md, go.mod
Syft changes has driven the need to require go 1.16. Also adds a badge indicator in our readme.
Closes #279
=> Bump go.mod minimum required go version to 1.16

go.mod, go.sum
This pulls in the updated CPE generation logic, which should reduce several false positive findings relative to the v0.10.2 release.
=> Update Syft to v0.15.1

grype/match/match.go, grype/matcher/common/cpe_matchers.go, grype/matcher/common/cpe_matchers_test.go, grype/matcher/common/distro_matchers.go, grype/matcher/common/distro_matchers_test.go, grype/matcher/common/language_matchers.go, grype/matcher/common/language_matchers_test.go, grype/matcher/common/utils_test.go, grype/vulnerability/store_adapter_test.go, grype/vulnerability/vulnerability.go
Adds a new `grypeDbNamespace` field to the match details indicating the namespace within grype-db that the match was found in.
Closes #283
=> Add grype db namespace indication in match details

go.mod, go.sum, grype/match/matcher_type.go, grype/matcher/controller.go, grype/matcher/msrc/matcher.go, grype/matcher/msrc/matcher_test.go, grype/version/constraint.go, grype/version/format.go, grype/version/kb_contraint.go, grype/version/kb_contraint_test.go, grype/version/kb_version.go, grype/version/rpm_constraint.go, grype/version/version.go, grype/vulnerability/namespace.go, grype/vulnerability/namespace_test.go, test/integration/match_coverage_test.go
This PR brings matching support for MSRC matching to Grype and requires Syft [changes](https://github.com/anchore/syft/pull/389) 
Closes #286 
From the following database metadata:
```
pk = 563027
id = CVE-2020-1556
record_source = microsoft:msrc:11646
package_name = Windows 10 Version 1903 for ARM64-based Systems
namespace = microsoft
version_constraint = 4517389 || 4524147 || 4524570 || 4528760 || 4530684 || 4532693 || 4540673 || 4549951 || 4556799 || 4560960 || 4565483
version_format = unknown
cpes = null
fixed_in_version = 4565351,4574727,4577671,4586786,4592449
```
And the following SBOM from Syft:
```json
{
"artifacts": [
{
"id": "30381e7b-497b-4d10-a70c-a9b1af8f7046",
"name": "Windows 10 Version 1903 for ARM64-based Systems",
"version": "4524570",
"type": "msrc-kb",
"foundBy": …
```
=> Support for MSRC matching

go.mod, go.sum, grype/match/matches.go, grype/match/matches_test.go, grype/presenter/models/document.go, grype/presenter/models/document_test.go
Sorts the JSON presenter output by vulnerability ID, package name, package version, then package type. This will help with more stable output when comparing two documents.
Closes #245
=> Add package sorting for artifacts in json document

grype/presenter/json/presenter_test.go, grype/presenter/json/test-fixtures/snapshot/TestJsonDirsPresenter.golden, grype/presenter/json/test-fixtures/snapshot/TestJsonImgsPresenter.golden, grype/presenter/models/package.go
Previously we removed the syft `pkg.Package.Metadata` field from being displayed as there is potentially a large amount of information, much which is not directly used in the matching process. Since then we have restricted the metadata field to only contain information that is pertinent to the matching process. The json presentation should be as transparent as possible about how matches are made, and now that irrelevant information has been pruned, it should be added back to the grype presentation model. Note: an equivalent `MetadataType` has not been added since it will not be directly used within grype and using the same values from syft could be misleading.
=> Show limited package metadata in json presenter

go.mod, go.sum, grype/pkg/java_metadata.go, grype/pkg/package.go, grype/pkg/package_test.go
The java virtual path is akin to the `Package.Locations` field except there is additional info that can track location information within nested jars with arbitrary depth. This brings further clarity as to which package exactly was matched on and exactly where it is. No other package type has this requirement, only java.
Testing was added to cover mapping of all package metadata from syft to the grype equivalent.
=> Add java virtual path to package metadata

go.mod, go.sum, internal/config/registry.go, internal/config/registry_test.go, test/cli/registry_auth_test.go
Related to anchore/stereoscope#68
Allows Grype to use registry credentials in cases where the user hasn't provided an "authority" config value
=> Allow registry auth config without authority value

.github/scripts/go_mod_tidy_check.sh, Makefile, go.sum
Our go.mod should always be tidy --this PR adds a specific linting step to verify this on each PR.
This is important during the release step, where we run `go mod download`, which may change the go.sum (putting the workspace into an unreleasable state). The current workaround is to run `go mod tidy` to re-tidy the `go.sum` after the `go mod download`. This is OK, however, the assumption is that the go.mod and go.sum were in a tidy state before the download. If this isn't the case then the git state will still be dirty and the workspace will be in an unreleasable state.
=> Add go.mod tidy CI check

.github/ISSUE_TEMPLATE/config.yml
This fixes the problem identified in Syft where outsiders aren't able to join our community Slack via the links we provide on the issue entry screen: https://github.com/anchore/syft/issues/423
(The analogous PR in Syft is https://github.com/anchore/syft/pull/424.)
=> Replace links to Slack channels with public signup link

test/grype-test-config.yaml, test/inline-compare/Makefile
Now that V3 DBs have been promoted to production the DB staging references for V3 should be removed to always test against product. Additionally the inline-compare tests have been updated to use the `./test/grype-test-config.yaml` for future configuration tweaks like this.
=> Remove v3 staging db references from test config

Makefile
Currently the check will always fail, this PR splits the check and the grep command to get the data into separate lines and ensures the if condition is always using bash (some systems may default to sh).
=> Correct validate-grype-test-target check

cmd/db_import.go
This change adds a description and positional arg in the usage text:
```
$ grype db import --help
import a vulnerability database archive from a local FILE.
DB archives can be obtained from "https://toolbox-data.anchore.io/grype/databases/listing.json".
Usage:
grype db import FILE [flags]
Flags:
-h, --help   help for import
Global Flags:
-c, --config string   application config file
-q, --quiet           suppress all logging output
-v, --verbose count   increase verbosity (-v = info, -vv = debug)
```
=> Add description + positional arg to help text for DB import

test/inline-compare/compare.py
[Now that RPM epoch is included in version info](https://github.com/anchore/grype/pull/331) we need to make certain that it is not included when comparing data fields against matches from inline-scan during validation.
Sample run locally with updates:
```
Gathering facts for debian:10.5
echo "Creating grype-reports/debian_10.5.json..."
Creating grype-reports/debian_10.5.json...
mkdir -p grype-reports
go run ../../main.go -c ../../test/grype-test-config.yaml debian:10.5 -o json > grype-reports/debian_10.5.json
✔ Vulnerability DB        [no update available]
✔ Loaded image
✔ Parsed image
✔ Cataloged packages      [91 packages]
✔ Scanned image           [108 vulnerabilities]
Gathering facts for centos:8.2.2004
echo "Creating grype-reports/centos_8.2.2004.json..."
Creating …
```
=> Update inline comparison script to ignore RPM epoch

grype/presenter/cyclonedx/document.go
The Grype scanner produces a CycloneDX Vulnerability Document which is in XML output with lower case component tags.
However the "Document" struct from this library has a Components tag that uses an upper case "Component". When the CycloneDX XML output is passed into a Document struct, it results in an empty Components array.
Fixing this issue https://github.com/anchore/grype/issues/345.
Signed-off-by: Robin Li <lrobin@vmware.com>
=> Modify Document struct Components tag to use lower case 'component'

grype/presenter/table/presenter.go
- Removes a lingering use of the "fixes indeterminate" term from the table output — now, if the fix state is unknown, the table output shows nothing in the "FIXED-IN" column.
=> Show no value in table output for unknown fixes

go.sum, grype/matcher/apk/matcher.go, grype/matcher/common/distro_matchers.go, grype/matcher/common/distro_matchers_test.go, grype/matcher/dpkg/matcher_mocks_test.go, grype/matcher/rpmdb/matcher_mocks_test.go, grype/vulnerability/provider.go, grype/vulnerability/store_adapter.go, grype/vulnerability/store_adapter_test.go
Fixes #353 
Adjusts the `ProviderByDistro` interface (and its implementation `StoreAdapter`) by having the `GetByDistro` method take a pointer to a distro, rather than just a distro. By doing so, matches don't need to check for `nil` distro values before asking the store provider to match by distro.
=> Fix panic from distro nil pointer dereference

grype/presenter/cyclonedx/test-fixtures/snapshot/TestCycloneDxPresenterDir.golden, grype/presenter/cyclonedx/test-fixtures/snapshot/TestCycloneDxPresenterImage.golden, grype/presenter/cyclonedx/vulnerability.go, grype/presenter/cyclonedx/vulnerability_test.go
Some feeds don't include CVSS but still report severity of a CVE
Fix #364 and #366
=> Always include severity in cyclonedx ratings

go.mod, go.sum, grype/matcher/msrc/matcher_test.go
Incorporates the changes made in https://github.com/anchore/grype-db/pull/32 into the tests asserting the correctness of MSRC related data from SBOM input.
Related to anchore/grype-db-builder#122
~Note: still in draft until https://github.com/anchore/grype-db/pull/32 is merged~
=> Update MSRC matching to include product ID in the suffix

README.md, go.mod, go.sum, internal/config/config.go, internal/config/registry.go, internal/config/registry_test.go, test/cli/registry_auth_test.go
As noted: this adds an option to connect to registries over http. This fixes #334 
Added just a very basic test, as this is just pushing configuration to `go-containerregistry`
Related to: https://github.com/anchore/syft/pull/482
=> Add option to enable connecting to registry over http #334

internal/file/tar.go, internal/file/tar_test.go
Today the tar helper is used to extract grype DB files from archives. However, it is possible for the grype DB to reach large sizes on development builds (up to 2GB currently). For this reason the maximum allowable file size in a tar needs to be raised (this threshold exists today to mitigate decompression bomb attacks).
=> Bump untar file size threshold

go.mod, go.sum
Upgrade to syft v0.21.0, which includes a change to skip certain files in `node_modules` directories, and fixes #385
=> Upgrade syft to 0.21.0. Fixes: #385

grype/matcher/common/distro_matchers.go, grype/matcher/rpmdb/matcher.go, grype/matcher/rpmdb/matcher_mocks_test.go, grype/matcher/rpmdb/matcher_test.go
Works to Address issues from:
Fixes #374 
Fixes #376
Update Regex to Capture Separate package groups
Refactor test to assert on public contract of Match
Add base case as first table
Adjust the matchBySourceIndirection helper function for the rpmdb matcher (grype/matcher/rpmdb/marcher.go) to use additional source version information to construct the correct upstream package to match against.
TODO:
=> (#374) - RPM Matcher - Package Name from Source Update

grype/matcher/apk/matcher_test.go, grype/matcher/common/distro_matchers.go, grype/matcher/common/distro_matchers_test.go, grype/matcher/common/utils_test.go, grype/matcher/rpmdb/matcher.go, grype/matcher/rpmdb/matcher_test.go, grype/pkg/rpmdb_metadata.go
This is a follow up from https://github.com/anchore/grype/issues/374 .
This PR makes two adjustments:
- When searching for possible upstream matches for RPM packages using the source RPM data, the current epoch, source version, and source release values are used to craft the package version used in the matching process.
- Package information is added to the `.matchDetails.[].searchedBy` map to clearly indicate the parameters that were used in the search. This is helpful in source-indirection is in play (the package and version from the source package, not the installed package, is used for matching) by indicating the source package information used in the search.
=> Include full ELVersion in RPM source-indirection matching

test/integration/db_mock_test.go, test/integration/match_by_image_test.go, test/integration/match_by_sbom_document_test.go, test/integration/test-fixtures/sbom/syft-sbom-with-kb-packages.json
Adds a test which exercises passing a syft SBOM with windows KB info that enables matching against mock MSRC vulnerability data.
=> Add integration test for MSRC matching

go.mod, go.sum, grype/matcher/apk/matcher.go, grype/matcher/apk/matcher_test.go, grype/pkg/apk_metadata.go, grype/pkg/package.go, grype/pkg/package_test.go, grype/version/fuzzy_constraint_test.go
This PR allows grype to match with source packages for alpine. It adds Metadata for APK packages that have OriginPackage reference. This is then used in the apk matcher to match against the origin package. 
After discussion with @wagoodman, it was decided that we would match the source just like we do with the actual package itself. In alpine, this is a multi step process. First it matches against secdb and then uses the cpes to also find matches within nvd. Matching the source package against secdb simply requires changing the name on the indirectPackage, but matching against nvd is a little more complicated. We decided to take all the cpes that are generated for the package and replace the package name with the source package. These cpes are then used to match against nvd
This PR also …
=> Alpine match source pkg

grype/version/constraint_unit.go, grype/version/fuzzy_constraint_test.go
Grype DB Builder was changed to use single quotes instead of double quotes for version constraints in [this PR](https://github.com/anchore/grype-db-builder/pull/146). This change broke constraint matching for vulndb records. This change fixes that by adding support for single quotes to the parseUnit function in `grype/version/constraint_unit.go`.
=> Fix vulndb fuzzy constraint matching

grype/version/constraint_unit_test.go
This PR adds tests for the new trimQuotes function added to `grype/version/constraint_unit.go`. I should have included this in my [original PR](https://github.com/anchore/grype/pull/415).
=> Add more unit tests for new trimQuotes function

.goreleaser.yaml, Makefile, cmd/version.go, internal/version/build.go
To Test run
```
make bootstrap
make build
```
Locally you should see syft version populated in the build:
When you run:
`./snapshot/grype-macos_darwin_amd64/grype version`
You should see syft version populated in the output:
=> Enhance version cmd

grype/cpe/cpe.go, grype/pkg/syft_json_provider_test.go, grype/pkg/test-fixtures/syft-java-bad-cpes.json
Partially addresses #417.
When Grype reads in a user-supplied SBOM from Syft, it needs to convert CPE strings into CPE objects. When malformed CPE strings are supplied, Grype errored out and provided no useful results.
This PR adjusts the CPE parsing logic (within Syft JSON parsing) to log a warning instead of returning an error in the scenario where a user-supplied CPE string cannot be parsed successfully, allowing the logic to continue to other CPEs and other packages that don't have any parsing issues.
**Note:** We should also make an adjustment in Syft to avoid the creation of malformed CPE strings.
=> Allow CPE parsing failures

.bouncer.yaml, .github/workflows/static-unit-integration.yaml, Makefile, go.mod, go.sum, grype/pkg/package.go, grype/pkg/package_test.go, grype/pkg/syft_json_provider.go, test/integration/compare_sbom_input_vs_lib_test.go, test/integration/test-fixtures/.gitignore, test/integration/utils_test.go
There is one failure in the tests right now, and that should get fixed by https://github.com/anchore/grype/pull/425.
This PR adds an integration test which compares the results of running grype against an image when the input comes from a syft sbom vs when the input comes from syft as a library.
The need for these tests comes from having discovered that the code that unmarshals the syft json was missing a handler for alpine metadata, and the code that transforms the metadata from syft as a library into grype's sbom format was missing the epoch field in RPM metadata.
The hope and intent of this test is to help developers catch scenarios where differences in sbom translation between both inputs cause vulnerability matches to get dropped.
The PR also includes bugfixes for the issues …
=> Bugfixes + Integration test for sbom input vs grype library comparison

grype/cpe/cpe.go
This is a follow-up to address this comment from a prior PR: https://github.com/anchore/grype/pull/425#discussion_r714288611
=> Improve log message for CPE parsing error

.github/workflows/release.yaml
This will automatically create an SBOM using Syft during the release phase and add it as a release artifact with the name `sbom.spdx.json`. Note: this depends on https://github.com/anchore/sbom-action/pull/68 in order to upload to draft releases
=> Add SBOM to releases

grype/match/matcher_type.go, grype/matcher/common/cpe_matchers.go, grype/matcher/controller.go, grype/matcher/stock/matcher.go, test/integration/db_mock_test.go, test/integration/match_by_sbom_document_test.go, test/integration/test-fixtures/sbom/syft-sbom-with-unknown-packages.json
Today if you input an SBOM into grype and there is a package with an unknown type then no vulnerability matching is done for that package. This PR adds a "stock" matcher (note: "default" is a reserve word in go); now any package will at least pass through this new stock matcher, which does CPE and language based matching.
=> Add default matcher (language + CPE matching)

go.mod, go.sum, grype/version/fuzzy_constraint.go, grype/version/fuzzy_constraint_test.go, grype/version/version_test.go
Pulls in the upstream grype-db change for allow for using a "good" default language namespace guess when searching for vulnerabilities for potentially supported languages.
Additionally this PR fixes version comparisons for the fuzzy version constraint checks where one side includes a `v` prefix while the other side does not. This is a common case for the `docker` golang package since docker changed the version scheme after the first few versions.
=> Add data-driven language matching

README.md, cmd/root.go, go.mod, grype/match/ignore.go, grype/match/ignore_test.go, grype/presenter/json/presenter.go, grype/presenter/json/presenter_test.go, grype/presenter/models/document.go, grype/presenter/models/document_test.go, grype/presenter/models/ignore.go, grype/presenter/models/ignore_test.go, grype/presenter/presenter.go, grype/presenter/template/presenter.go, grype/presenter/template/presenter_test.go, internal/config/config.go
Closes #198 
This PR introduces an "ignore" mechanism where users can specify one or more "ignore rules" that cause Grype not to show vulnerability matches for which these rules apply (and to _not_ consider these vulnerability matches when evaluating the `--fail-on` gate).
The implementation design can be found in #198. But here's a recap of the "rule" data structure, since it's helpful in discussing this PR's implementation...
```go
type IgnoreRule struct {
Vulnerability string
Package       IgnoreRulePackage
}
type IgnoreRulePackage struct {
Name     string
Version  string
Location string
}
```
1. ~Rules can specify a `Location` to match a package's "location" within a vulnerability match. Packages themselves can have _1 to N_ locations. Currently, this part of the "ignore rule" is …
=> Feature: Specifying "ignore rules" for vulnerability matches

.bouncer.yaml, go.mod, go.sum, grype/pkg/syft_sbom_provider.go, test/integration/compare_sbom_input_vs_lib_test.go, test/integration/utils_test.go
- Add a new exception for OR license for `github.com/spdx/tools-golang`
- update syft version in go.mod
- run `go mod tidy` and generate new go.sum
- update `syft_sbom_provider` to use new signature for generating SBOM from the library
- update integration tests to use new `Encode` `Decode` pattern
- add `PhpComposerPkg` to exception list for integration test
=> Bump syft version => v0.30.1

go.mod, go.sum
Upgrade grype to use latest DB
Without the latest version of the `grype-db` the vulnerability results for rockylinux are incomplete:
**This screenshot shows what's on main:**
**This screenshot shows what's on this PR with the latest database:**
=> bump grype-db to tip of main

cmd/event_loop.go
There is no need to log bus unsubscribe errors (e.g. "unable to find subscription to unsubscribe" errors) as this is not actionable.
=> Ignore partybus unsubscribe errors

.goreleaser.yaml
Builds and publishes grype images with consistency in relation to how syft is published.
I ran the build command locally to generate the images and `v` is not prefixed.
=> update releaser code to tag with correct v prefix

README.md, cmd/cmd.go, cmd/db_check.go, cmd/db_delete.go, cmd/db_import.go, cmd/db_list.go, cmd/db_update.go, cmd/util.go, cmd/version.go, grype/db/curator.go
Adds the ability to list entries discovered available DBs from the configured update URL (`db.update-url`)"
```
❯ syft db list
Built:    2021-11-22 08:13:50 +0000 UTC
URL:      https://toolbox-data.anchore.io/grype/databases/vulnerability-db_v3_2021-11-22T08:13:50Z.tar.gz
Checksum: sha256:b45e70819ab48d469cf4bbdb8a1fb41673f3465730885c49a1779bcdda5e6357
Built:    2021-11-21 08:15:44 +0000 UTC
URL:      https://toolbox-data.anchore.io/grype/databases/vulnerability-db_v3_2021-11-21T08:15:44Z.tar.gz
Checksum: sha256:c402d01fa909a3fa85a5c6733ef27a3a51a9105b6c62b9152adbd24c08358911
...
Built:    2021-06-02 10:24:36 +0000 UTC
URL:      https://toolbox-data.anchore.io/grype/databases/vulnerability-db_v3_2021-06-02T10:24:36Z.tar.gz
Checksum: …
```
=> Add db list command

grype/db/curator.go, grype/presenter/template/presenter.go, internal/file/copy.go, internal/logger/logrus.go, internal/version/update.go, test/integration/compare_sbom_input_vs_lib_test.go
The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
=> refactor: move from io/ioutil to io and os packages

grype/pkg/package.go, grype/pkg/package_test.go
Fixes #548 
This PR prevents a panic in Grype that can occur in `pkg.FromCatalog`.
Since it's currently possible for `catalog.Sorted()` to return more items than the return value of `catalog.PackageCount()` indicates, this PR adjusts the loop such that:
- An `index out of range` panic is no longer possible, since slice items aren't being addressed by index.
- The **benefit** of avoiding unnecessary allocations for the `result` slice's underlying array is **preserved** for the case where the return value of `catalog.PackageCount()` is greater than or equal to `len(catalog.Sorted())` (which is the expected case).
=> Fix panic in FromCatalog function

install.sh
See #560 for details and investigation.
This adds a `.` following the path in the `cp` command under `extract_from_dmg` to enhance compatibility with `coreutils`
=> update so install.sh is compatible with coreutils 

README.md
The command in the docs was wrong, updated to reflect the actual command required
=> fix(docs): fix issue with template command example

go.mod, go.sum
Fixes #592 by incorporating https://github.com/anchore/syft/pull/750.
=> Bump syft to include file source fix

README.md, go.mod, go.sum, grype/presenter/template/presenter.go, grype/presenter/template/test-fixtures/snapshot/TestPresenter_Present.golden, grype/presenter/template/test-fixtures/test.template
This commit adds a set of common templating functions from https://masterminds.github.io/sprig/ which makes it easier to deal with go templates and dramatically improves what is possible with custom grype outputs.
=> Add sprig templating functions for grype output

go.mod, go.sum
Resolves:
https://security.archlinux.org/CVE-2021-43565
`20210921155107-089bfa567519` < `v0.0.0-20211202192323-5770296d904e`
Bump to `2022xxx`
=> update golang crypto library dependency

go.mod, go.sum, grype/presenter/models/source.go, grype/presenter/models/source_test.go
Includes partially the features from https://github.com/anchore/syft/releases/tag/v0.38.0
=> Bump syft to v0.38.0 for release

.github/workflows/release.yaml, install.sh, test/install/Makefile
The sbom-action installation failed in the latest release run: https://github.com/anchore/grype/runs/5205757120?check_suite_focus=truecheck_suite_focus=true
```
[info] checking github for release tag='v0.33.0' 
[debug] http_download(url=[anchore/syft/releases/v0.33.0)](https://github.com/anchore/syft/releases/v0.33.0)) 
[info] using release tag='v0.33.0' version='0.33.0' os='darwin' arch='amd64' 
[debug] downloading files into /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp.97tmb50y 
[debug] http_download(url=[v0.33.0 syft_0.33.0_checksums.txt) (download)](https://github.com/anchore/syft/releases/download/v0.33.0/syft_0.33.0_checksums.txt)) 
Error:  could not find release asset for os='darwin' arch='amd64' format='tar.gz'  
Error:  failed to install syft 
Error: ENOENT: no such file …
```
=> Upgrade install.sh to support installations for previous versions

Dockerfile
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Fixes #613
=> Enhance container image labels for ArtifactHub

grype/presenter/json/test-fixtures/snapshot/TestEmptyJsonPresenter.golden, grype/presenter/json/test-fixtures/snapshot/TestJsonDirsPresenter.golden, grype/presenter/json/test-fixtures/snapshot/TestJsonImgsPresenter.golden, grype/presenter/models/distribution.go, grype/presenter/template/test-fixtures/snapshot/TestPresenter_Present.golden
This PR fixes the output of the JSON distro block from work done with https://github.com/anchore/syft/pull/742 and https://github.com/anchore/grype/pull/585 . Specifically, the mapping of the raw `linux.Distribution` struct during presentation is mapping the incorrect fields.
Additionally, it is more accurate to use the specific strong distro types that grype uses during matching (which was selected in this PR).
Example of the original distro block behavior between syft and grype:
```
docker run --rm anchore/syft:v0.35.1 -o json alpine:3.15 | jq .distro
{
"name": "alpine",
"version": "3.15.0",
"idLike": ""
}
```
```
docker run --rm anchore/grype:v0.27.3 -o json alpine:3.15 | jq .distro
{
"name": "alpine",
"version": "3.15.0",
"idLike": ""
}
```
Example of the new (bad) behavior of the …
=> Restore behavior of JSON distro block

.github/workflows/codeql-analysis.yml, .github/workflows/validations.yaml, test/install/test_harness.sh
This PR mirrors the syft changes from https://github.com/anchore/syft/pull/858
- Adds polling check for install tests to ensure the snapshot server is up
- Elevates CodeQL to only run on main (not on PRs)
- De-duplicates checks as best as possible; CI checks only run on PRs and pushes to main. Pushes to feature branches will no longer trigger CI.
=> reduce PR CI pain and flakyness

go.mod, grype/db/curator.go, internal/file/getter.go
This PR does a couple things:
- restores the original decompressors list to match that of `hashicorp/go-getter` used in the `grype db update` execution path
- adds more decompressors to the `grype db import` path
This paves the way for replacing `gzip` DB archives for `zstd` DB archives in the future.
=> Add additional DB archive decompressors

artifacthub-repo.yml
Config is documented here: [https://github.com/artifacthub/hub/blob/v1.6.0/docs/metadata/artifacthub-repo.yml](https://github.com/artifacthub/hub/blob/v1.6.0/docs/metadata/artifacthub-repo.yml?rgh-link-date=2022-03-09T12%3A32%3A51Z)
This PR is meant only to establish ownership, a future PR will add the repo ID and more owners.
=> Add artifacthub owner

grype/presenter/sarif/presenter.go, grype/presenter/sarif/presenter_test.go
Got a SIGSEGV when outputting SARIF in one unexplained case; this should prevent that from happening.
=> Fix nil pointer access in SARIF output

grype/presenter/sarif/presenter.go, grype/presenter/sarif/presenter_test.go, grype/presenter/sarif/test-fixtures/snapshot/TestSarifPresenterDir.golden
SARIF is used for submitting to GitHub's security alerts. There is an issue with directory scans that results in relative paths being prefixed by `/`, resulting in the file "not found" in the repository when looking at the Code scanning alerts page.
=> Correct issue with SARIF dir scan relative paths

go.mod, go.sum
Updating to the latest Syft release, which includes fixes for decoding CycloneDX
=> Update Syft to 0.42.1

grype/presenter/sarif/presenter.go, grype/presenter/sarif/presenter_test.go, grype/presenter/sarif/test-fixtures/snapshot/TestSarifPresenterDir.golden, grype/presenter/sarif/test-fixtures/snapshot/TestSarifPresenterImage.golden
In SARIF output, which is used by GitHub to display security findings, we need to best represent the files found during directory scans so they may match files within a repository, this corrects one case and adds a number of test cases for different Grype invocations: cwd, relative, and absolute paths.
Additionally, we don't really need a lot of precision for the severity, so we now limit this to 1 decimal place.
=> Improve SARIF path handling and severity

.github/workflows/release.yaml, .github/workflows/validations.yaml, Makefile, grype/presenter/sarif/presenter.go
- Remove golangci-lint go1.17 job
- Upgrade golanci-lint to 1.45.0
- Tiny code change suggested by gocritic linter
=> Upgrade CI to go1.18

go.mod, go.sum
Pull in fix from https://github.com/scylladb/go-set/commit/cc7b2070d91ebf40d233207b633e28f5bd8f03a5 to prevent compile issues on 32 bit architectures:
```bash
$ GOOS=linux GOARCH=386 go build  -o /tmp/out examples/basic.go
../../.gvm/pkgsets/go1.18/global/pkg/mod/github.com/scylladb/go-set@v1.0.2/strset/strset.go:248:13: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in assignment (overflows)
../../.gvm/pkgsets/go1.18/global/pkg/mod/github.com/scylladb/go-set@v1.0.2/strset/strset.go:255:16: math.MaxInt64 (untyped int constant 9223372036854775807) overflows int
$ go get -d github.com/scylladb/go-set@master
go: downloading github.com/scylladb/go-set v1.0.3-0.20200225121959-cc7b2070d91e
go: upgraded github.com/scylladb/go-set v1.0.2 => …
```
=> Bump strset version to fix 386 builds

grype/match/sort.go, grype/presenter/models/match.go, grype/presenter/template/presenter.go
Add a `byName` custom function for custom template consumers.
Example template:
```
TYPE   NAME                 INSTALLED    VULN                 SEVERITY     FIXED?   FIXED IN     UPSTREAM PACKAGE
{{- range .Matches | byMatchName}}
{{printf "%-6s %-20s %-12s %-20s %-12s %-8s %-12s %s" .Artifact.Type .Artifact.Name .Artifact.Version .Vulnerability.ID .Vulnerability.Severity .Vulnerability.Fix.State (.Vulnerability.Fix.Versions | join ", ") (.Artifact.Upstreams | join ", ")}}
{{- end}}
```
Note the `|` for `Matches` to be sorted.
Using the above template run:
```
grype alpine:3.14.1 -o template -t mycustom.tmpl
```
Output should now be able to be sorted by name for custom templates:
=> Add byMatchName custom function for custom template users

grype/presenter/cyclonedx/presenter_test.go, grype/presenter/sarif/presenter_test.go, grype/presenter/table/presenter.go, grype/presenter/table/presenter_test.go, grype/presenter/table/test-fixtures/snapshot/TestTablePresenter.golden
This helps avoid confusion between packages of the same name but different types.
Examples where I've hit this recently:
- `tar` is a node package as well as a linux executable apk/rpm/deb
- `msgpack` is a node package but also a python package
- `jsonpointer` is also the name of both a node and a python package
In each case when I saw the vuln reported in grype output I started investigating the "wrong" one (call me unlucky!) and it took some digging to realise the issue.
The "type" is a succinct representation of _where_ Grype found this package, so hopefully including this should make things a lot clearer.
I'm aware of the templating functionality with `-o` however:
1. I've struggled to make a custom text-tabular format in order to simply add that column while retaining the nice …
=> Include package type in table output

.github/workflows/update-syft-release.yml
This PR adds a workflow that will automatically create a PR to update Syft if the released version of Syft is higher than what is specified in Grype. This will allow us to:
* More easily bump the Syft version if that's the only thing needed for a Grype release
* More quickly identify things that need to be fixed if upgrading the Syft release causes build or tests to fail
NOTE: this may have some added noise in the case we commit `syft@some-hash` instead of a release tag.
Unfortunately, we can't even test this until it gets merged into `main`...
=> Add workflow for automatic PR for new Syft releases

grype/matcher/java/matcher.go
The warning was too noisy for the default output. Reduce to `Debug` so users can view via `-vv`
=> reduce log level for warning so not in default output for upstream matcher

grype/match/matches.go, grype/match/matches_test.go
A helper for consumers that is looking to see a set of vulnerabilities for each package in a collection of matches.
=> Add matches helper

go.mod, go.sum
Incorporates https://github.com/anchore/syft/pull/963
=> Preserve package IDs on Syft JSON SBOM decode

README.md
Hi,
Your tool rocks. Si wanted to embed it as part of our CI. The GH action exists but is not documented on the README.
=> Add the Grype-based GitHub Action to the README

cmd/root.go, go.mod, go.sum
This PR:
- Pulls in Syft `v0.45.1`, which includes fixes that reduce Syft's portion of log warnings (https://github.com/anchore/syft/pull/976, https://github.com/anchore/syft/pull/977, and https://github.com/anchore/syft/pull/983)
- Stops warning when a Linux distro cannot be detected. It's expected that we won't detect the Linux distro in cases where the filesystem scope specified by the user doesn't include any distro identification files.
Fixes #684
=> address excessive warnings from multiple sources

README.md, go.mod, go.sum, grype/db/v3/namespace.go, grype/db/v3/namespace_test.go, grype/match/matcher_type.go, grype/matcher/dotnet/matcher.go, grype/matcher/matchers.go, grype/pkg/package_test.go, test/integration/compare_sbom_input_vs_lib_test.go, test/integration/db_mock_test.go, test/integration/match_by_image_test.go, test/integration/test-fixtures/image-debian-match-coverage/dotnet/TestLibrary.deps.json
Signed-off-by: Christian Kotzbauer <git@ckotzbauer.de>
This PR updates syft to 0.46.0 and adds support for dotnet.
Tested locally with an dotnet-image with vulnerable packages.
Has to be rebased when #746 is merged.
closes #736
=> Add syft v0.46.0 Dotnet support

README.md
Hi all,
Was looking through the docs and I couldn't understand the possible values for logging levels.
I looked through the code and saw that you're using logrus.
So, this PR is to update the README docs to add a reference to those levels for those who may be unsure whether the tool uses standard levels or not. 
(happy to adjust this to just list the levels if that's prefered.)
=> Add reference to logrus logging levels

.goreleaser.yaml
In cases where a draft is released and not published, users will encounter brew install issues along with other friction regarding the new release.
Bumping this to just cut a release with note/artifact edits being done after the fact will reduce this friction.
=> publish release to reduce user friction

README.md, grype/match/ignore.go, grype/match/ignore_test.go
Adds support for ignoring vulnerability matches based off of the vulnerability namespace as well as the package language
=> Support namespace and language as additional criteria for ignoring vulnerability matches

README.md, cmd/root.go, go.mod, go.sum, grype/db/curator.go, grype/db/curator_test.go, internal/config/database.go, internal/ui/etui_event_handlers.go
* Add staleness check to vuln db. Execution fails if db is 5 or more days old.  Configurable via `grype.yaml` and enabled by default. 
* Warn user that db is stale even when staleness check is disabled.
* Add version banner comparing application version with new version available illustrating  to users how far behind their local grype is.
FIx: #240 
Note on staleness field type: it uses go's time duration notation. Anchore provides daily updates. However users might use grype with a different database and different release schedules. Go's duration notation has flexible granularity to different use cases. It also helps maintaining grype's config file consistent over time.
Signed-off-by: Jonas Xavier <jonasx@anchore.com>
=> add db staleness check

grype/presenter/config.go, grype/presenter/template/presenter.go, grype/presenter/template/test-fixtures/test.valid.template
This change fixes problems with parsing templates with custom functions (like defined in `sprig` package) by using accepted `FuncMap` to parse the template.
Fixes https://github.com/anchore/grype/issues/784
=> fix: accept templates with custom functions

README.md
Add golang to the documentation. It is supported by Grype so it should be in the language specific package list
Closes https://github.com/anchore/grype/issues/787
=> fix: add golang to documentation

README.md
Sorry for missing this in the last pr. `github:composer` is listed in the database as a namespace, so it should be reflected in the readme that Grype supports php
Closes https://github.com/anchore/grype/issues/792
=> docs: update to include php

README.md
Added some confusion in closing https://github.com/anchore/grype/issues/792 as seen in https://github.com/anchore/grype/issues/797. Changing the docs to read more similar to [Syft's composer statement](https://github.com/anchore/syft/blob/main/README.md?plain=1#L40) which doesn't mention the `composer.json` file since it isn't indexed by Syft. Rather `installed.json` and `composer.lock` is indexed since they contain actual module version resolutions.
Closes: https://github.com/anchore/grype/issues/797
=> docs: update php listing to be more clear that the `.json` file isn't indexed

cmd/db_update.go, grype/event/event.go, grype/event/parsers/parsers.go, internal/ui/common_event_handlers.go, internal/ui/ephemeral_terminal_ui.go, internal/ui/logger_ui.go
Currently this command publishes to partybus and I'd expect some UI on it, but it doesn't run in the event loop to properly publish. Adding this `event.NonRootCommandFinished` construct will be useful in the db diff command since the command will take some time and it would be helpful for a user to be able to track the progress for it.
Closes: https://github.com/anchore/grype/issues/805
=> fix: add support for partybus ui on `grype db update` cmd

cmd/root.go, grype/db/curator.go, grype/db/db_closer.go, grype/db/v4/store.go, grype/db/v4/store/store.go, grype/differ/differ.go, grype/lib.go, test/integration/compare_sbom_input_vs_lib_test.go
add DBCloser interface to LoadVulnerabilityDB() function. Clients can avoid db connection leak if vulnerability db is loaded many times.
Important for tools like https://github.com/ckotzbauer/vulnerability-operator which loads vulnerability db periodically during its runtime cycle.
Signed-off-by: Sergey Artamonov <artsv79@gmail.com>
=> add DBCloser. Clients can aviod db connection leak if vulnerability db is loaded many times

README.md, cmd/root.go, internal/config/application.go
Adds a `--only-notfixed` flag as a sister flag to the `--only-fixed` flag.
Closes https://github.com/anchore/grype/issues/824
=> feat: add --only-notfixed flag

schema/cyclonedxvex/Makefile, schema/cyclonedxvex/cyclonedx.xsd
The schema fix is from
https://github.com/CycloneDX/specification/issues/147
Signed-off-by: Josh Bressers <josh@bress.net>
=> Fix a cyclonedxvex typo and fix the schema document

grype/match/matcher_type.go, grype/matcher/golang/matcher.go, grype/matcher/golang/matcher_test.go, grype/matcher/golang/mather.go, grype/matcher/matchers.go, grype/pkg/golang_bin_metadata.go, grype/pkg/metadata.go, grype/pkg/package.go, grype/pkg/package_test.go, test/integration/db_mock_test.go, test/integration/match_by_image_test.go, test/integration/test-fixtures/image-debian-match-coverage/Dockerfile, test/integration/test-fixtures/image-debian-match-coverage/golang/go.mod, test/integration/test-fixtures/image-debian-match-coverage/golang/go.sum, test/integration/test-fixtures/image-debian-match-coverage/golang/main.go
This PR drops match support in grype on the MAIN golang module to reduce the false positives being reported.
This drop is done by adding a custom Golang matcher that does a `search.ByCriteria` only if `package.Name` does not equal `package.Metadata.MainModule`
4 months ago syft introduced including the main golang module for a given package into the SBOM
-myApp (devel) <------------- Main Golang Module
- dependency1 (v1.0.0)
- dependency2 (v0.5.0)
- ...
This month we enhanced the reporting on that main module by building in package information compiled with the go binary:
Ex: devel ===> v0.0.0-20220606222826-f59ce19ec6b6
Problem: 
We have no way currently of updating the `v0.0.0` portion of the tag since currently there is no standard way to inject the latest VCS tags into the compile …
=> Add new matcher files for golang => remove main module FP matches

grype/search/cpe.go, grype/search/cpe_test.go, grype/search/only_vulnerable_targets.go
In terms of addressing the concerns from the issue, I processed all the cpes, curtesy of @westonsteimel's [cpe repo](https://github.com/westonsteimel/nvd-data-analysis/tree/main/data/cpe), and identified the ~10k different possible product|vendor|target_sw pairings. I manually evaluated 200 of these from the set of those supported by Syft ~1500 (13%) and saw no language wrapping where filtering would cause a bad mismatch. [Work here](https://gist.github.com/cpendery/82aadba917c2dd380cf9de4ed5743899).
Add's support for filtering out vulnerabilities where every cpe's target software does not match the package's language and has the loosest possible filtering by including all target software's that Syft doesn't support regardless of if a match is found or not to reduce missed …
=> feat: add filtering support using target software field in cpe

cmd/root.go
Small help menu update to space out relevant syft instructions
Before:
After:
=> add new line for help block

cmd/db_diff.go
Just flips the base/target urls back the correct direction for the default case of no urls provided
Closes: https://github.com/anchore/grype/issues/844
=> fix: db diff default has flipped base/target url

grype/db/internal/gormadapter/open.go
If running multiple instances of Grype, it is possible to get errors due to the way the database is opened, for example, running:
```shell
for i in `seq 1 15`
do
go run main.go alpine:latest >> output.log 2>&1 &      
done
```
This PR opens the database in readonly mode, which prevents these types of errors.
=> Ensure database access is readonly

grype/db/internal/gormadapter/open.go
Solves #855 
The only one I don't see here is `_journal_mode=WAL`
https://www.sqlite.org/uri.html#uri_filenames_in_sqlite
https://www.sqlite.org/c3ref/open.html <-- Immutable ref
https://www.sqlite.org/wal.html <-- WAL ref
https://www.sqlite.org/sharedcache.html#sqlite_shared_cache_mode <-- Cache ref
https://www.sqlite.org/uri.html#uri_filenames_in_sqlite <-- mode=ro ref
```
immutable=1
cache=shared
mode=ro
_journal_mode=WAL
```
=> additional readOptions added  per 855

cmd/root.go, cmd/root_test.go
This PR ensures that Grype first tries to uses the following logic for warning a user about a missing distribution
1. Try to use the app config for the distribution
2. Try to use the context which has a distribution produced by Syft for formats that support it
3. Check if any packages would require a distribution
If the final state is reached where there is no distribution known and a distribution package exists, then throw the warning, but return it to warning level
Closes https://github.com/anchore/grype/issues/748
=> fix: only show distro warning if distro packages exist

grype/search/cpe_test.go, grype/search/only_vulnerable_targets.go
Java packages are known to embed other ecosystem packages within them, so we don't want to currently make this assumption for any java language type packages
=> disable CPE match filtering based on target software component for java packages

DEVELOPING.md, README.md
Add a small blurb about building from source and how to run using go in DEVELOPING.md.
Closes #581
=> Add blurbs about building and running from source

README.md, cmd/root.go
(Draft until https://github.com/anchore/syft/issues/1189 addressed, likely via https://github.com/anchore/stereoscope/pull/142)
Add Singularity example to "supported sources" in README, and to image sources in online help.
=> docs: improve Singularity image source docs

README.md, cmd/root.go, grype/matcher/dotnet/matcher.go, grype/matcher/golang/matcher.go, grype/matcher/java/matcher.go, grype/matcher/javascript/matcher.go, grype/matcher/matchers.go, grype/matcher/python/matcher.go, grype/matcher/ruby/matcher.go, grype/matcher/stock/matcher.go, grype/search/criteria.go, internal/config/application.go, internal/config/datasources.go, internal/config/match.go, test/integration/match_by_sbom_document_test.go
As discussed by @westonsteimel today, this pr puts the logic for turning on cpe matching for the language specific matchers & stock matcher into the config. Currently on by default, though this behavior will potentially change on the Gitlab data source is added
=> feat: extract use cpes in matching logic to be configurable

.goreleaser_docker.yaml
The current docker assets are not being published due to a bug in the go releaser templates:
https://github.com/anchore/grype/actions/runs/2973469646
This PR removes the old typos and adds a debug/reg image under the `dockers` config.
The addition of these two images resolves the manifest issue. These images can now be included as expected image templates since they are once again being published.
=> remove arch typo - add debug/reg s390x

go.mod, go.sum, grype/match/matcher_type.go, grype/matcher/matchers.go, grype/matcher/rpm/matcher.go, grype/matcher/rpm/matcher_mocks_test.go, grype/matcher/rpm/matcher_test.go, grype/pkg/metadata.go, grype/pkg/package.go, grype/pkg/package_test.go, grype/pkg/rpm_metadata.go, grype/presenter/json/presenter_test.go, grype/presenter/json/test-fixtures/snapshot/TestJsonImgsPresenter.golden, grype/version/format.go, test/cli/test-fixtures/sbom-grype-source.json, test/integration/match_by_image_test.go
This PR is a follow-on to https://github.com/anchore/syft/pull/1188, which adds support for scanning RPM files. This aligns the naming from `Rpmdb` to `Rpm` in a number of places.
Closes #570 
NOTE: scanning RPM files for vulnerabilities may not work as desired, as there is no Linux distribution identified. In the case there are RPMs identified, it may be required to specify a distribution, which requires knowing which _version_ to use:
```
% grype ~/Downloads/rpm 
✔ Vulnerability DB        [no update available]
✔ Indexed /Users/kzantow/Downloads/rpm 
✔ Cataloged packages      [1 packages]
✔ Scanned image           [0 vulnerabilities]
[0000]  WARN Unable to determine the OS distribution. This may result in missing vulnerabilities. You may specify a distro using: --distro …
```
=> Add support for scanning RPM files

grype/pkg/purl_provider.go, grype/pkg/purl_provider_test.go, grype/pkg/test-fixtures/valid-purl.txt
This PR fixes incorrect JSON output when using PURL input, which was caused by all Packages having an empty ID.
Fixes #967
=> PURL input results in incorrect artifact in JSON output

grype/db/v5/namespace/index.go, grype/db/v5/namespace/index_test.go, grype/db/vulnerability_provider.go, grype/matcher/apk/matcher.go, grype/matcher/matchers.go
Partial Fix for #964 
When scanning `alpine:edge` with grype the incorrect vulnerability namespace would be used causing false positives that would already be fixed in the upstream source:
https://security.alpinelinux.org/branch/edge-main
https://gitlab.alpinelinux.org/ariadne/secfixes-tracker
This fix treats nil distro version segments (a product of a version string that could not be parsed), when distro is of type `alpine`, as the signal for returning the `alpine:edge` namespace.
Please read the related issue for upstream recommendations on reducing the false positives produced by this PR. 
=> fix: update case for alpine:edge correct vuln feed

test/quality/.yardstick.yaml
Update the quality gate with the latest images and labels.  Use syft v0.60.1 for SBOM generation in order to enable the node binary analysis result matching
=> chore: grype quality pipeline latest label and image updates

grype/search/only_vulnerable_targets.go, grype/search/only_vulnerable_targets_test.go
Enhances the CPE target software component match filtering logic to consider ecosystems which aren't currently supported by syft cataloging but are well-known sources of false-positives. This currently adds support for filtering various permutations of `wordpress`, `joomla`, and `drupal`
=> feat: consider well-known false-positive generating CPE target SW components in match filtering logic

.github/workflows/codeql-analysis.yml, .gitignore, Makefile
After merging #988 it was observed that the codeql action needed to be upgraded as well as have its permissions refined a bit further. This PR adds:
```
permissions:
security-events: write
```
Per the documentation found here:
https://github.com/github/codeql-action#usage
It also scopes it under the job rather than at the top level of the workflow file, but I am unsure if that has an effect on the OSS score-card. 
The versions have also been bumped and pinned to deal with the following warning found in this build:
https://github.com/anchore/grype/actions/runs/3461743751/jobs/5779738191
`Warning: CodeQL Action v1 will be deprecated on December 7th, 2022. Please upgrade to v2.`
Path awareness has also been added to save runs on docs, tests, or other nonmainline code changes.
The go module …
=> chore: update codeql to pinned v2 with correct write permissions

.github/scripts/apple-signing/notarize.sh, .github/workflows/release.yaml, .github/workflows/update-bootstrap-tools.yml, .github/workflows/update-syft-release.yml, .github/workflows/validations.yaml, Dockerfile, Dockerfile.debug, Dockerfile.dev, test/integration/test-fixtures/image-debian-match-coverage/Dockerfile
With the addition of the scorecard utility, we've been able to identify dependencies that can be pinned to specific versions. This PR takes a stab at reducing some of the initial warnings. 
=> chore: pin dependencies

grype/db/v3/namespace.go, grype/db/v3/namespace_test.go, grype/db/v4/namespace/distro/namespace_test.go, grype/db/v5/namespace/distro/namespace_test.go, grype/distro/distro_test.go, grype/distro/test-fixtures/os/wolfi/etc/os-release, grype/distro/type.go
Adds a strong distro type for [Wolfi OS](https://github.com/wolfi-dev/).  Although we aren't yet populating a vulnerability feed namespace for it, because it is a rolling distro we will want to ignore mapping the version surfaced from the linux release and instead use a constant value like `rolling` or `live`.  We could also leave the version component of the namespace as an empty string, I just don't know if that's confusing.  So for a v5 namespace it'd be one of these:
- `wolfi:distro:wolfi:rolling`
- `wolfi:distro:wolfi:live`
- `wolfi:distro:wolfi:`
- something else?
=> feat: add strong distro type for wolfi

grype/db/v3/namespace.go, grype/db/v3/namespace_test.go, grype/db/v4/namespace/index.go, grype/db/v4/namespace/index_test.go, grype/db/v5/namespace/index.go, grype/db/v5/namespace/index_test.go, grype/distro/distro.go
Adds support for building the correct vulnerability namespaces for rolling distros.  This will allow matching against distro-specific feeds once a namespace is populated within the grype database.  It will only return the new rolling namespace for a distro once it is being populated in the loaded index from the grype database, so will ensure fallback to CPE-based matching until the corresponding vuln drivers are implemented and released
=> feat: vulnerability namespacing support for rolling distros

Dockerfile, Dockerfile.debug
The base container images were swapped between normal distroless and debug.
Fixes #1010
=> fix: swapped base container images

grype/presenter/table/presenter.go
If the same package is found with different versions, table output is not stable. This PR corrects the issue. E.g.:
Before:
```
busybox       1.23.2-r3             apk     CVE-2016-2148     Critical
busybox       1.23.2                binary  CVE-2021-42381    High
busybox       1.23.2                binary  CVE-2016-2148     Critical
busybox       1.23.2-r3             apk     CVE-2018-20679    High
busybox       1.23.2                binary  CVE-2021-42384    High
busybox       1.23.2                binary  CVE-2017-16544    High
busybox       1.23.2                binary  CVE-2018-20679    High
busybox       1.23.2                binary  CVE-2021-42385    High
busybox       1.23.2-r3             apk     CVE-2021-42385    High
busybox       1.23.2                binary  CVE-2016-2147 …
```
=> fix: table format sorting

test/quality/README.md
For people unfamiliar with Python, it may be confusing what steps to use to run the quality gate locally as well as `yardstick` to update vulnerability match information. Hopefully these docs will make this more clear.
=> docs: update quality gate docs

grype/pkg/package.go, grype/pkg/package_test.go, grype/pkg/syft_provider.go, grype/pkg/syft_sbom_provider.go
This PR adjust the package exclusions baesd on ownership-by-file-overlap relationships. Before:
```
$ grype cgr.dev/chainguard/wolfi-base:latest -q 
NAME        INSTALLED  FIXED-IN  TYPE  VULNERABILITY   SEVERITY 
busybox     1.35.0                     CVE-2022-28391  High      
busybox     1.35.0                     CVE-2022-30065  High      
libcrypto3  3.0.7-r0             apk   CVE-2022-3996   High      
libssl3     3.0.7-r0             apk   CVE-2022-3996   High 
```
After:
```
grype cgr.dev/chainguard/wolfi-base:latest -q 
NAME        INSTALLED  FIXED-IN  TYPE  VULNERABILITY  SEVERITY 
libcrypto3  3.0.7-r0             apk   CVE-2022-3996  High      
libssl3     3.0.7-r0             apk   CVE-2022-3996  High  
```
Fixes #1044 -- but NOTE: we are planning on moving some of this …
=> fix: update removing results based on ownership-by-file-overlap

go.mod, go.sum, grype/cpe/cpe.go, grype/cpe/cpe_test.go, grype/db/vulnerability_provider.go, grype/db/vulnerability_provider_test.go, grype/match/match.go, grype/matcher/apk/matcher_test.go, grype/matcher/golang/matcher_test.go, grype/matcher/java/matcher_mocks_test.go, grype/matcher/portage/matcher_mocks_test.go, grype/matcher/rpm/matcher_mocks_test.go, grype/pkg/package.go, grype/pkg/package_test.go, grype/pkg/purl_provider.go, grype/pkg/syft_sbom_provider_test.go, grype/pkg/upstream_package.go, grype/pkg/upstream_package_test.go, grype/presenter/models/models_helpers.go, grype/search/cpe.go, grype/search/cpe_test.go, grype/version/version.go, grype/vulnerability/provider.go, grype/vulnerability/vulnerability.go, grype/vulnerability_matcher_test.go, test/integration/match_by_image_test.go
This PR corrects an issue when orienting results by CVE that may result in related vulnerabilities and CPEs being lost in output during the match merge process. This was also the cause of an intermittent test failure, which _should_ now be resolved.
=> fix: orient by cve merging

grype/presenter/cyclonedx/presenter.go, grype/presenter/cyclonedx/presenter_test.go, grype/presenter/cyclonedx/test-fixtures/snapshot/TestCycloneDxPresenterDir.golden, grype/presenter/cyclonedx/test-fixtures/snapshot/TestCycloneDxPresenterImage.golden
This PR provides more consistent output and fixes an issue which was causing [intermittent test failures](https://github.com/anchore/grype/actions/runs/3792582903/jobs/6448895986#step:8:76) by sorting vulnerability results when outputting CycloneDX formats.
This also swaps to use JSON in tests, because it is much easier to determine where differences are than a bytewise XML diff.
=> fix: sort vulnerability results

test/quality/requirements.txt
This PR updates the quality gate yardstick to print more errors if unable to get the latest grype version from the github api.
=> chore: update yardstick to diagnose intermittent quality gate test failures

.github/workflows/validations.yaml
This PR adds the `GITHUB_TOKEN` to the quality test environment to attempt to solve intermittent failures to access the GitHub API to get the latest version of Grype.
=> chore: add github token to quality tests

cmd/db_diff.go, grype/differ/differ.go, grype/differ/differ_test.go, grype/differ/test-fixtures/dbs/base/5/metadata.json, grype/differ/test-fixtures/dbs/base/5/vulnerability.db, grype/differ/test-fixtures/dbs/target/5/metadata.json, grype/differ/test-fixtures/dbs/target/5/vulnerability.db
This change allows both URLs and local file directories to be used with the `grype db diff` command, e.g.
```shell
grype db diff db-1 db-2
```
Where `db-1` and `db-2` are both directories containing a grype db. This means each db must have the following structure:
```
<dir>/
<db-version>/
metadata.json
vulnerability.db
```
currently, `db-1` would then be:
```
db-1/
5/
metadata.json
vulnerability.db
```
Fixes: #1059
=> feat: allow grype db diff to specify local db directories

grype/match/explicit_ignores.go, grype/match/explicit_ignores_test.go
Fixes #558 
Let me know if there's a better way to cancel these out in the code. I saw this method used for some log4j FPs so I continued that approach here.
One unfortunate drawback to this approach is the UI becomes a bit confusing:
```console
$ go run . anchore/grype   
✔ Vulnerability DB        [no update available]
✔ Parsed image            
✔ Cataloged packages      [212 packages]
✔ Scanned image           [2 vulnerabilities]
No vulnerabilities found
```
"2 vulnerabilities", and then "no vulnerabilities". Curious if anyone has thoughts to make this more straightforward.
=> Add protobuf FPs to default ignore list

grype/presenter/cyclonedx/vulnerability.go, grype/presenter/cyclonedx/vulnerability_test.go
This PR restores previous behavior that severity is always output in CycloneDX format.
Fixes #1066
=> fix: always include severity in cyclonedx output

.github/dependabot.yaml
=> chore: enable dependabot on gomod and GitHub actions

test/quality/requirements.txt
Incorporates https://github.com/anchore/yardstick/pull/24 into our quality gate checks as to alleviate the GitHub rate limits we're seeing in the pipeline.
=> bump yardstick to 2d30ea7429d0a59020e0176bba1b3b6b8b01b08a

grype/search/only_vulnerable_targets.go
=> fix: exclude OS packages from CPE target filtering

grype/distro/distro.go, grype/matcher/matchers.go
Support for Arch Linux was added without parsing the vulnerability tracker from Arch Linux, resulting in false positives.
Disabled until proper coverage can be done.
Example:
$ grype archlinux
✔ Vulnerability DB        [updated]
✔ Parsed image
✔ Cataloged packages      [113 packages]
✔ Scanned image           [5 vulnerabilities]
NAME        INSTALLED   FIXED-IN  TYPE  VULNERABILITY   SEVERITY
gnupg       2.2.40-1              alpm  CVE-2022-34903  Medium
gnupg       2.2.40-1              alpm  CVE-2022-3515   Critical
libarchive  3.6.2-2               alpm  CVE-2022-36227  Critical
zlib        1:1.2.13-2            alpm  CVE-2018-25032  High
zlib        1:1.2.13-2            alpm  CVE-2022-37434  Critical
Where CVE-2022-37434 is fixed by zlib version 1:1.2.12-3. …
=> distro: Disable support for Arch Linux

grype/matcher/apk/matcher.go, grype/matcher/apk/matcher_test.go, grype/search/cpe.go
Previously, the -r{buildindex} suffix of APK package versions were treated as pre-release versions per the fuzzy matcher logic; however, these should be treated as equivalent to the release version for the purposes of collecting CPE-based matches for APK packages.
We may want to make a similar change in syft to generate cleaner CPE versions for APK packages, but making the change in grype corrects behaviour for previously-generated SBOMs as well.
=> fix: correct APK CPE version comparison logic

internal/config/match.go
CPE-based matching leads to a large amount of false positives, and disabling it by default for the javascript matcher seems like a reasonable first step since GitHub owns NPM and already has coverage of NPM-related security advisories in the Github Security Advisory dataset
=> feat: disable CPE-based matching by default for javascript

grype/vulnerability_matcher.go, grype/vulnerability_matcher_test.go
This changes the `--by-cve` logic to only reorient the vulnerability metadata around NVD data rather than attempting to get the corresponding vulnerability table record.  This will address performance concerns since their was no index on `id, namespace` on the vulnerabilities table, but there is on the `vulnerability_metadata` table.  This also preserves the fixed in information from the actual match rather than losing it since the NVD data has no fix info.  It also correctly returns the CVE identifier in cases where there is more than one vulnerability record for a given `id, namespace` since that is the primary key on the `vulnerability_metadata` table.
Fixes #1185
=> fix: by-cpe pivot by vuln metadata rather than vulnerability record

README.md, cmd/root.go, grype/pkg/provider_config.go, grype/pkg/syft_provider.go, internal/config/application.go
Follow up to https://github.com/anchore/syft/pull/1703
https://github.com/anchore/grype/issues/1204 surfaces the need for allowing a user to express a preference over the `default-image-pull-source` to be used when building an SBOM for vulnerability scanning.
This adds a config option into grype to consume the new syft behavior.
There is also a small boy scout change that includes the `name` flag (it was part of the function signature being edited for pull source) which was introduced into syft recently. `name` is used to provide users an override for naming the source. `name` and `default-image-pull-source` have been added into the syft provider config.
=> feat: default image source config option

grype/presenter/json/presenter_test.go, grype/presenter/json/test-fixtures/snapshot/TestEmptyJsonPresenter.golden, grype/presenter/json/test-fixtures/snapshot/TestJsonDirsPresenter.golden, grype/presenter/json/test-fixtures/snapshot/TestJsonImgsPresenter.golden, grype/presenter/models/descriptor.go, grype/presenter/models/document.go, grype/presenter/models/document_test.go
Adds timestamp into the JSON Output, timestamp is a new field inside Descriptor.
Unit tests were a little fiddly because the timestamp changes so first check the value is not nil and is in RFC 3339 format, then essentially use the normal assert.JSONEq to check the rest of the document(s).
=> feat: add timestamp to json output (#1170)

grype/pkg/purl_provider.go
Fix false positive for purl provider
- To fix this, updated the purl_provider to have an epoch variable:
- defaults to 0
- if epoch= set in the purl file it grabs that value
- if epoch not in front of version it is added, version=epoch:version
Closes #1031
**Testing**:
purl file `dbus.purl`
```purl
pkg:rpm/dbus@1.12.8-18.el8?arch=x86_64&epoch=1
```
command used:
```bash
go run main.go purl:dbus.purl --distro rhel:8.6
```
output without fix:
```bash
✔ Vulnerability DB        [no update available]
✔ Scanning image...       [6 vulnerabilities]
├── 0 critical, 2 high, 3 medium, 1 low, 0 negligible
└── 5 fixed
NAME  INSTALLED      FIXED-IN             TYPE  VULNERABILITY   SEVERITY 
dbus  1.12.8-18.el8  (won't fix)          rpm   CVE-2020-35512  Low       
dbus  1.12.8-18.el8 …
```
=> Fix false positive for purl provider

Makefile, test/integration/test-fixtures/skopeo-policy.json, test/integration/utils_test.go
The "make integration" target assumes that skopeo will be available on PATH, but this wasn't documented. Install it during bootstrap when other utilities are installed. (See ./test/integration/utils_test.go:50). Include a sample skopeo policy.json, otherwise skopeo will look for a missing policy doc a /etc/containers/policy.json and exit with an error. The sample policy document matches the one included by default with "brew install skopeo".
1. Is `./test/integration/test-fixtures/skopeo-policy.json` the right place for this file?
2. Are the contents of `skopeo-policy.json` what we want?
3. Should the test fall back to `skopeo` on path if it's available? IMO no, since it would make the test depend more on the environment where it was run, but wanted to call out this behavior change.
4. I …
=> Install skopeo during bootstrap

README.md
The output format is already supported:
`supported formats are: [json table cyclonedx cyclonedx-json sarif template]`
CycloneDX 1.4 is also there:
https://github.com/anchore/grype/issues/591
=> docs: add "cyclonedx-json" to output formats

cmd/cmd.go
s/form-lib/from-lib
Reported as part of https://github.com/anchore/grype/issues/1244, but the main fix will need to be in Syft I believe, at https://github.com/anchore/syft/blob/75d625b697e85283b688c4d7cb7addf7e2854a58/syft/formats/syftjson/to_syft_model.go#L197
Note: I've added the `changelog-ignore` label because I don't think this needs to be in release notes.
=> chore: Fix logger prefix

cmd/root.go, grype/pkg/syft_sbom_provider.go, internal/input.go
I figured out that running `cat syft.json | grype` works but `grype < syft.json` does not work. This happens, because the IsPipedInput method only checks if stdin is a pipe which will be false if stdin is fed by a redirect.
The go idiomatic way to fix this is by just checking if the file produced by stat has a size > 0.
Implemented this check, that will recognize stdin by redirect, in the `IsPipedInput()` method. Renamed the method to `IsStdinPipeOrRedirect()`.
=> Fix reading syft json from stdin by redirect

grype/db/v5/vulnerability_metadata.go, grype/presenter/models/cvss.go, grype/vulnerability/metadata.go
Adds source and type to the CVSS score information to allow identification of the organization that submitted the score and whether they are a primary or secondary source.
=> feat: add source and type to CVSS information

grype/presenter/models/models_helpers.go, grype/presenter/presenter.go, grype/presenter/table/presenter.go, grype/presenter/table/presenter_test.go, grype/presenter/table/test-fixtures/snapshot/TestDisplaysIgnoredMatches.golden, grype/presenter/table/test-fixtures/snapshot/TestHidesIgnoredMatches.golden
Closes https://github.com/anchore/grype/issues/1053
This PR fixes a bug where suppressed vulnerabilities are displayed even though the `--show-suppressed` flag is not provided. The fix is made by checking the value of the `showSuppressed` option before including the suppressed vulns in the result. This PR also adds tests to assert the behaviour with/without `--show-suppressed`.
=> Hide suppressed vulnerabilities when --show-suppressed is not given

grype/matcher/apk/matcher_test.go, grype/search/cpe.go, grype/search/cpe_test.go, grype/search/language.go, grype/search/language_test.go, grype/vulnerability_matcher_test.go, test/integration/match_by_image_test.go, test/integration/match_by_sbom_document_test.go
This adds the package name and version that were searched by to the match details in grype output for all matchers.  Previously this detail was only surfaced when searching by distro.
=> feat: add package info to search by for all match details

grype/db/v5/pkg/qualifier/from_json.go
Logs unsupported package qualifiers at `debug` level rather than `warning`.  The message is only meant to convey that there are new qualifiers available in grype-db that the version of grype being used cannot take advantage of to improve matching behavior; however, the warning is confusing to users and may make it seem like grype is in a broken state.
=> chore: log unsupported package qualifier as debug

templates/README.md, templates/table.tmpl
This is a start on #1316 - Unsure whether this fixes #629 or more work is needed to fix the issues.
I've included a template that mimics the table output of Grype, it's not great (see the README) and it can be optimised further by adding some helper functions into the presenter FuncMap but it works and it's a start.
Biggest pain is it's sorted by the CVE (I think) but like I said, it's a start.
Fixed-In is a list so I concatenated the fields in the template but I couldn't find an example with multiple fix versions so can't provide a shiny screenshot sorry
Potentially more documentation could go in the README about extracting the json models so people know what fields are available etc.
=> feat: add community template folder and new table template

grype/match/explicit_ignores.go, grype/match/explicit_ignores_test.go, grype/matcher/matchers.go
This PR fixes a problem where the totals being reported did not always match the vulnerabilities displayed. The issue is that some filtering occurred for known invalid matches _after_ the totals were added.
Fixes #1312
=> fix: totals for vulnerability matches

README.md, templates/csv.tmpl
- add the csv.tmpl to templates/ directory
- edit README.md to match
=> Add a simple CSV format template to the templates/ directory and tweak docs

DEVELOPING.md
Developing in Docker is no longer explicitly supported. Update developing docs to reflect this.
Fixes https://github.com/anchore/grype/issues/1234
=> Remove Docker section from DEVELOPING.md

cmd/grype/cli/legacy/root.go
Previously, the wrong path would get passed, and the template file would get truncated.
Fixes https://github.com/anchore/grype/issues/1388
Manual testing done:
```
❯ go run cmd/grype/main.go -o template=foo.csv -o json -t templates/csv.tmpl alpine:latest
✔ Vulnerability DB                [no update available]  
✔ Loaded image                                                                                                                                                                                               alpine:latest
✔ Parsed image                                                                                                                                     sha256:5053b247d78b5e43b5543fec77c856ce70b8dc705d9f38336fa77736f25ff47c
✔ Cataloged packages              [16 packages] …
```
=> Pass correct output file

cmd/grype/cli/legacy/event_loop.go, test/cli/cmd_test.go
Fixes https://github.com/anchore/grype/issues/1392.
=> fix: vulnerabilities should be printed when `--fail-on` fails

test/quality/gate.py
Permit piping "make validate" to a file without filling it with control characters.
=> chore: in quality tests, only colorize quality ouput if in a tty

grype/presenter/table/presenter.go, grype/presenter/table/presenter_test.go, grype/presenter/table/test-fixtures/snapshot/TestDisplaysIgnoredMatches.golden
This PR updates the table sort in the default table presenter with the following priority:
- name
- version
- type
- severity
- vulnerability
TODO
=> feat: update table sort to be name, version, type, severity, vulnerability

grype/presenter/json/presenter_test.go, grype/presenter/models/document.go, grype/presenter/models/document_test.go, grype/presenter/models/match.go, grype/presenter/models/vulnerability_metadata.go, grype/presenter/table/presenter.go, grype/presenter/template/presenter.go
Another submission for #709 
Implements the new table sorting secondary sort for the default json output.
There is a small side effect which influences the template presenter since it uses the same sorting interface as the json output.
Do you think we should do the same here for sarif and cyclonedx? I'm unsure here and only have made changes for formats we have agency over at the moment (table, json, template).
=> feat: implement secondary sorting for default json output

cmd/grype/internal/ui/ui.go, grype/pkg/syft_provider.go
This PR ports the changes from https://github.com/anchore/syft/pull/1968 to Grype, which fixes some hang conditions.
=> fix: some hang conditions

.github/workflows/validations.yaml, test/quality/.yardstick.yaml
This ensures the CPE dict enhancements are taken into account for future quality gate comparisons.  This should wait until https://github.com/anchore/vulnerability-match-labels/pull/92 makes it in
=> chore: use syft v0.86.1 in the quality gate tests

test/quality/.yardstick.yaml, test/quality/gate.py, test/quality/requirements.txt
Include changes to gate.py to correctly guess that local builds of grype are considered the changed version, not the latest release.
=> chore: use latest yardstick

Makefile
Enables "make lint" to be run after "make quality". Previously, the linter rules that prohibit ":" in any filename would fail if the yardstick or vulnerability-match-labels directories had been initialized (e.g. if "make quality" had been run), since they have filenames like "sha256:abcd" in them. Exclude them from this lint, since they are not go files.
Test case where repo has yardstick state, and thus files with ":":
1. Run `make` in test/quality to get some yardstick state in the workspace
2. Prove that there are a lot of files with `:` in the name: `find . | grep -e ":" | wc -l` prints ~17k.
3. Run `make lint` from the root of this workspace; it succeeds.
Running `make lint` on main, before this change, if the yardstick state is initialized, fails like this:
```
❯ make lint
Running …
```
=> chore: exclude yardstick store from filename rules

test/quality/Makefile
Previously, if a user cloned grype without passing "--recurse-submodules", the makefile under test/quality would fail to initialize the submodule, resulting in unexpected behavior. Always initialize the submodule if it's missing.
```
git clone -b init-submodule-if-missing git@github.com:anchore/grype
cd grype/test/quality
vim .yardstick.yaml # comment out most of the images so this doesn't take forever
make
ls vulnerability-match-labels # see that the directory is actually initialized and has stuff in it.
```
=> Init submodule if missing

test/quality/.yardstick.yaml
To take into account recent maven PURL generation improvements.  https://github.com/anchore/vulnerability-match-labels/pull/101 should be merged first to ensure the sbom cache is updated
=> chore: bump to syft v0.87.1 in quality gate

grype/pkg/package.go, grype/pkg/package_test.go
Previously, ownership by file overlap would remove packages of the same type, or packages with an empty type. Instead, only remove packages by overlap if the owned package is binary, since the installation source of the binary will have better version info than the binary itself.
=> fix: Only remove packages by binary overlap

cmd/grype/internal/ui/__snapshots__/post_ui_event_writer_test.snap, cmd/grype/internal/ui/post_ui_event_writer.go, cmd/grype/internal/ui/post_ui_event_writer_test.go
Currently when running grype and there is a new version available the version is shown with no other context:
This PR addresses this by filling in the notice text:
=> New version notice only showing the version and no text

README.md
We will stop supporting v1 and v2 DB schemas in the near future. This PR adds a notice to the README as to which versions of Grype are supported and the consequences of using unsupported versions.
=> Explicitly note supported versions of Grype

test/quality/.gitignore, test/quality/.yardstick.yaml, test/quality/Makefile
Ultimately the goal of the quality gate in grype is to test the effectiveness of grype itself to detect vulnerabilities in an artifact. This is done relative to the set of labels we know about these artifacts. The gate today has two moving targets: the grype code itself and the vulnerability DB. This PR changes this such that the only independent variable is the grype code itself by pinning the DB to a single version.
=> Pin the vulnerability DB used in quality gate testing

grype/version/portage_version.go, grype/version/portage_version_test.go
This PR corrects a portage version comparison issue.
Fixes: #1459
=> fix: portage version comparison

test/quality/.yardstick.yaml
Should be merged after https://github.com/anchore/vulnerability-match-labels/pull/110
=> chore: bump quality gate to use syft v0.89.0

go.mod
Our understanding is that without the patch version, every run of "go mod tidy" will write a toolchain directive in the file, which will result in a diff from contributors with different point versions of go, which is noisy and prone to breaking CI.
Thanks to https://github.com/golang/go/issues/62278#issuecomment-1698829945 for the concise explanation of what seems to be going on with the changes to go.mod.
=> chore: Update go declaration to have point version

Makefile, go.mod, go.sum, grype/db/curator.go, grype/differ/differ.go
Fix the race conditions from setting stage.Current from multiple go routines by upgrading to a newer version of go-progress that includes an atomic version of stager and using that. Enable race detection on unit tests, and on a single invocation of the main command under the integration target.
=> chore: Fix race conditions around stager, enable detector

.github/workflows/oss-project-board-add.yaml, .github/workflows/release.yaml, .github/workflows/validations.yaml, test/cli/test-fixtures/image-java-subprocess/Dockerfile, test/cli/test-fixtures/image-node-subprocess/Dockerfile, test/install/environments/Dockerfile-alpine-3.6, test/install/environments/Dockerfile-ubuntu-20.04
This PR takes a few steps on the github actions side of our code to protect against potential security threats.
- Updates All Github Actions to be pinned by sha (please double check there are no shortened commit sha here)
- Updates container images to be pinned by sha256
- Updates top level security permissions of workflows to be default `READ` (writes can still be scoped to individual steps eg: releases)
For the Audit I used https://github.com/ossf/scorecard#basic-usage with the `--show-details` flag. The sections I looked at for this PR were:
[Dangerous-Workflow](https://github.com/ossf/scorecard/blob/main/docs/checks.md#dangerous-workflow)
[Pinned-Dependencies](https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies) …
=> chore: pin actions; pin images; add top level action permissions

cmd/grype/cli/cli.go, go.mod, go.sum
This PR corrects an issue that the `grype version` command was not outputting the current db schema version.
=> fix: version output including supported db schema

README.md
Fixes a minor typo in the newly added VEX content on the README
=> Fix typo in flag on Readme

cmd/grype/cli/cli.go, cmd/grype/cli/commands/db_check.go, cmd/grype/cli/commands/db_delete.go, cmd/grype/cli/commands/db_diff.go, cmd/grype/cli/commands/db_import.go, cmd/grype/cli/commands/db_list.go, cmd/grype/cli/commands/db_status.go, cmd/grype/cli/commands/db_update.go, cmd/grype/cli/commands/root.go, cmd/grype/cli/commands/update.go, cmd/grype/cli/commands/util.go, cmd/grype/cli/commands/util_test.go, cmd/grype/internal/constants.go, cmd/grype/internal/ui/no_ui.go, cmd/grype/internal/ui/ui.go, cmd/grype/main.go, go.mod, go.sum, grype/event/event.go, grype/vulnerability_matcher.go, internal/bus/helpers.go
This PR corrects an issue where the terminal cursor wasn't being restored after certain errors occur. For example, running:
```
grype docker:asdf.asdf
```
or 
```
grype alpine:3.15 --fail-on high
```
... both resulted in an error being returned from the command, resulting in the terminal getting clobbered _most of the time_, but this was actually due to a race condition, so occasionally it did not happen.
Additionally, this PR:
* Cleans up a few items from the CLIO port
* Restores the TUI elements for showing image / cataloging progress
* Reworks the `runGrype` function a bit to be easier to understand
* Removes the `internal.Grype` constant altogether
Fixes: #1492
=> fix: terminal clobbering when commands return errors

.gitignore, go.mod, grype/search/cpe_test.go, grype/version/constraint.go, grype/version/fuzzy_constraint_test.go, grype/version/pep440_constraint.go, grype/version/pep440_constraint_test.go, grype/version/pep440_version.go, grype/version/version.go, test/integration/db_mock_test.go, test/integration/match_by_sbom_document_test.go, test/integration/test-fixtures/sbom/syft-sbom-with-unknown-packages.json
There have been several issues opened where `certifi` Python package, which uses a version string like `2022.07.22`, which is PEP440 compliant but may or may not look like semver depending on the regex in use, results in incorrect version comparisons. Switch python version comparison to use Python PEP440 directly.
Fixes https://github.com/anchore/grype/issues/1430
Fixes https://github.com/anchore/grype/issues/1417
Fixes https://github.com/anchore/grype/issues/1172
Fixes https://github.com/anchore/grype/issues/1034
Fixes https://github.com/anchore/grype/issues/986
=> fix: use PEP440 for Python package version comparison

go.mod, go.sum
Pulls in a fix to go-progress so that scanning large images no longer results in a data race in the UI code.
=> chore: bump stereoscope to fix data race in UI

grype/version/constraint.go
Now that we're using a real PEP440 library, there's no need for this comment.
Was pointed out at https://github.com/anchore/grype/pull/1510#discussion_r1337007669
=> chore: remove outdated comment about fuzzy matching python versions

internal/format/writer_test.go
Closes #1534 by replacing the conditional with just the content of one of its branches.
=> fix: `if` with identical `then` and `else` blocks in `internal/format/writer_test.go`

cmd/grype/cli/commands/root.go, test/cli/cmd_test.go
This PR corrects an oversight that the `descriptor` block was empty (and analogous other locations in other formats).
Fixes: #1538
=> fix: empty descriptor name and version

.github/workflows/validations.yaml, cmd/grype/cli/options/match.go, grype/db/v5/namespace/index_test.go, grype/db/v5/namespace/language/namespace_test.go, grype/match/matcher_type.go, grype/matcher/matchers.go, grype/matcher/rust/matcher.go, test/grype-test-config.yaml, test/integration/db_mock_test.go, test/integration/match_by_image_test.go, test/integration/test-fixtures/image-rust-auditable-match-coverage/Dockerfile
Disables CPE-based matching for ecosystems which are covered by GitHub Security Advisories.  Also adds a separate rust matcher and related configuration to allow configuring CPE-based matching off for rust packages while still leaving it enabled for anything falling into the stock matcher.
Fixes: #811
=> feat: disable CPE-based matching for GHSA ecosystems by default

.github/workflows/release.yaml, .goreleaser.yaml, README.md
Changes:
- Add checksum signing using cosign in goreleaser
- Update release workflow to have cosign installed
- Add artifact verification steps to README.md
Closes https://github.com/anchore/grype/issues/1513
=> Add checksum signing

go.mod, go.sum
Pull in https://github.com/anchore/clio/pull/29 to fix a regression (errors should be shown to stderr not stdout).
=> Report errors to stderr not stdout

README.md, cmd/grype/cli/commands/root.go, cmd/grype/cli/options/match.go, grype/matcher/golang/matcher.go, grype/matcher/golang/matcher_test.go
Fixes #1562 
This PR introduces a new config option `match.golang.always-use-cpe-for-stdlib` (defaulting to true) allowing the golang matcher to search for the stdlib package by CPE even if CPE matching is disabled. 
We lean primarily on GHSA matching for the golang ecosystem, however, there are still cases specifically for the stdlib where the data in NVD is preferred for matching. Take for example [CVE-2023-24537](https://nvd.nist.gov/vuln/detail/CVE-2023-24537) , which matches to `golang:go` when `< 1.19.8` (and other ranges), however the [GHSA](https://github.com/advisories/GHSA-fp86-2355-v99r) data does not have a suggested package for this (yet) . This can lead to potential false positives, say  in the case of [CVE-2022-27664](https://nvd.nist.gov/vuln/detail/CVE-2022-27664) where …
=> Add exception for go stdlib search by CPE

.github/workflows/validations.yaml
Mimics what was implemented on https://github.com/anchore/vunnel/pull/364 , allowing for uploading archives to help replicate the CI state when using yardstick locally.
=> Capture quality gate state on failures

.github/workflows/validations.yaml
Otherwise, archive step fails like https://github.com/anchore/grype/actions/runs/6668040742/job/18122746110#step:5:12
```sh
tar: tests/quality: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Error: Process completed with exit code 2.
```
=> chore: fix path to quality tests

grype/db/v5/namespace/index.go, grype/version/fuzzy_constraint.go
We should use `(*regexp.Regexp).MatchString` instead of `(*regexp.Regexp).Match([]byte(...))` when matching string to avoid unnecessary `[]byte` conversions and reduce allocations. A one-line change for free performance improvement.
Example benchmark:
```go
func BenchmarkMatch(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := pseudoSemverPattern.Match([]byte("1.0.0-beta-prerelease")); !match {
b.Fail()
}
}
}
func BenchmarkMatchString(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := pseudoSemverPattern.MatchString("1.0.0-beta-prerelease"); !match {
b.Fail()
}
}
}
```
Result:
```
goos: linux
goarch: amd64
pkg: github.com/anchore/grype/grype/version
cpu: AMD Ryzen 7 PRO 4750U with Radeon Graphics
BenchmarkMatch-16          	 1378789	       889.7 ns/op	      24 B/op	       1 …
```
=> perf: avoid allocations with `(*regexp.Regexp).MatchString`

grype/db/v5/namespace/index.go, grype/db/v5/namespace/index_test.go, grype/distro/distro.go, grype/distro/distro_test.go
Fixes #1446 
Works by special casing `debian:unstable` to skip semver creation / parsing in a couple of places.
(`go run cmd/grype/main.go` is this change, `grype` is v0.73.0 from homebrew)
``` sh
❯ go run cmd/grype/main.go r-base:latest
✔ Vulnerability DB                [no update available]
✔ Loaded image                                                                                                                                                                                                                                                                                                                                           r-base:latest
✔ Parsed image …
```
=> feat: match against debian unstable

grype/search/cpe_test.go, grype/version/constraint.go, grype/version/format.go, grype/version/golang_constraint.go, grype/version/golang_constraint_test.go, grype/version/golang_version.go, grype/version/golang_version_test.go, grype/version/version.go
Resolves https://github.com/anchore/grype/issues/1581
Right now, go versions are handled by generic semantic version comparison (or fall through to fuzzy version comparison sometimes). There are a few ways in which the version found in a `go.mod` for example is not exactly a semver string:
1. Sometimes, the go tooling appends `+incompatible` to a version string. This causes the comparison to fall through from semantic version to fuzzy version, which is the root cause of #1581.
2. Versions of the go standard library itself start with `go` (e.g. `go1.24.1`) instead of `v`.
3. Go dependencies can be declared based on commits, rather than semver tags, which results in a string that looks like `v0.0.0-20180116102854-5a71ef0e047d`. Right now, these are working because the lexicographical …
=> fix: golang version parsing

test/quality/.yardstick.yaml
Merge https://github.com/anchore/vulnerability-match-labels/pull/124 first and wait for sbom cache rebuild
=> chore: bump to syft v0.98.0 in quality gate tests

README.md
After porting to CLIO, README was not updated to reflect changes in the logging configuration. The file is now updated based on `grype --help` output which is already up to date.
This closes #1645
=> Fix logging configuration in README

cmd/grype/cli/commands/root.go, cmd/grype/cli/options/grype.go, grype/vex/processor_test.go, grype/vex/testdata/vex-docs/openvex-debian.json, grype/vulnerability_matcher.go, grype/vulnerability_matcher_test.go
Previously, VEX documents provided to Grype when --fail-on was set were not
taken into account. That led to inconsistent behaviour where a vulnerability
would be ignored when only `--vex` was specified, but would be included in
Grype output when both `--vex` and `--fail-on` were specified.
This change fixes that by moving the failure severity check to after the VEX
documents provided are tested.
I have also added a unit test to check that the combination of VEX docs and
failure severity checks works as expected.
I also took the opportunity to fix some typos while I was poking around.
fixes https://github.com/anchore/grype/issues/1639
=> fix: take VEX docs into account when --fail-on is set

grype/cpe/cpe.go, grype/pkg/purl_provider.go, test/integration/match_by_image_test.go
Previously, Syft's cpe.CPE type was an alias for wfn.Attributes. Fix a couple places where Grype's compilation depended on that fact, since it will stop being true in the next Syft release.
See anchore/syft#2529
=> chore: break assumption that syft cpe.CPE is wfn.Attributes

.github/scripts/check-syft-version-is-release.sh, .github/scripts/trigger-release.sh, .github/workflows/release.yaml
This is an extra protection that ensures the version of syft in the `go.mod` is a released version of syft (not a version that is for a commit on main). This is done in both the release workflow as well as the trigger for release -- this is done in both places to help balance ease (fail as early as possible) and safety (the source of truth for all release gates must be in the release workflow).
This should allow us to continually integrate syft changes in grype more often and not require a release of syft.
=> Ensure releases only use released versions of syft

grype/matcher/apk/matcher_test.go, grype/pkg/package.go, grype/search/cpe.go, grype/search/cpe_test.go, grype/search/criteria.go
Previously, a warning would be logged about missing CPEs even when processing packages for which CPEs would never be generated. Instead, return a specific error when attempting to match by CPEs on a package with no CPEs.
This change improves the user experience in 2 ways:
1. The user will only see a warning about missing CPEs if Grype actually tries to search by CPE on a package that has no CPEs, which means the warning is only ever shown if it's affecting matchign
2. The warning contains the package name, so the user has a better ability to try to investigate.
But with the following tradeoff:
1. If the user has a lot of packages missing CPEs for a matcher that has CPE matching turned on, they will see this log line a lot of times.
Fixes #1634 
Before, even with CPE matching disabled 
``` …
```
=> fix: only warn missing CPEs if CPEs wanted

README.md
I figured that, mainly for symmetry with https://github.com/anchore/syft, this should be mentioned.
It could be a good indication the Chocolatey version is at least not malicious.
=> Added instruction to install with choco

grype/presenter/sarif/presenter.go, grype/presenter/sarif/presenter_test.go, grype/presenter/sarif/test-fixtures/snapshot/TestSarifPresenter_directory.golden, grype/presenter/sarif/test-fixtures/snapshot/TestSarifPresenter_image.golden
This PR improves the descriptive text when outputting SARIF to display more information to the user including the image/ and tag or sha that was specified. [An example of what this looks like in GitHub can be seen here](https://github.com/kzantow-anchore/test-sarif/security/code-scanning/38).
Fixes #1715
=> fix: improve sarif descriptive text and fingerprint

test/install/Makefile, test/quality/Makefile
This PR updates the vulnerability database used in quality tests. And also applies [the fix from Syft](https://github.com/anchore/syft/pull/2663) for failing busybox install tests.
=> chore(test): update quality test grype db

install.sh
As the main function was not the last command, it did always return a zero status code. Exiting right after main allows us to return the actual return code instead.
Analogous to https://github.com/anchore/syft/pull/2664 .
=> fix(install): return right exit codes

grype/matcher/apk/matcher.go, grype/search/distro.go, grype/search/language.go, grype/version/golang_version.go, grype/version/golang_version_test.go, grype/version/version.go
Today when you are matching against a golang package with a devel version, you see this warning:
```
[0000]  WARN could not match by package language (package=Pkg(type=go-module, name=./staging/src/k8s.io/api, version=(devel), upstreams=0)): matcher failed to parse version pkg="./staging/src/k8s.io/api" ver="(devel)": Malformed version: (devel)
```
However, this case is quite common, and there is nothing the user can do about this so we should not be showing this warning.
This PR makes the following changes:
- an explicit error case that other version constructors can use in the future
- changes this to a trace log
=> Suppress warnings when matching go packages with `devel` version

Makefile
GO111MODULE=off GOBIN=/home/xxx/code/grype/.tmp go get -u golang.org/x/perf/cmd/benchstat
go: modules disabled by GO111MODULE=off; see 'go help modules'
make: *** [Makefile:112: bootstrap-tools] Error 1
=> fix: make bootstrap-tools failed

cmd/grype/cli/options/database.go, grype/db/curator.go, grype/db/curator_test.go
Otherwise grype db commands can hang if the CDN is having issues.
Related to https://github.com/anchore/grype/issues/1731
We don't want commands like `grype db update` to hang indefinitely, and we certain don't want `grype <some-source>` to hang indefinitely.
Grype is already intended to continue on error if db updates are not available: https://github.com/anchore/grype/blob/fix%2Foverall-http-timeout/grype/db/curator.go#L142, so after this change, a timeout error when checking for update or downloading the database will result in a logged warning.
30 seconds overall timeout seems be reasonable. The compressed grype db as of this writing is ~152MB .tar.gz file when downloaded. I've done a few `time curl -o /dev/null "${DB_URL}"` for grype dbs published on different days, and the highest …
=> fix: enable http timeout

README.md, cmd/grype/cli/commands/root.go, cmd/grype/cli/options/grype.go, grype/match/ignore.go, grype/match/ignore_test.go, grype/presenter/models/ignore.go
Adds ignoring of kernel-headers indirect matches on kernel vulns since the kernel-headers package does not have the kernel code in it that kernel vulns are actually referring to.
Adds a config value to control this ignore behavior that defaults to enabling the ignore rules.
Fixes: #1762
* Adds ignore rule support for match types and upstream package names.
* Adds default ignore rules for kernel-headers indirect matches on kernel for rpms.
=> fix: adds ignore rules for kernel-headers indirect matches

grype/matcher/golang/matcher.go, grype/matcher/golang/matcher_test.go, grype/version/golang_version_test.go
Previously, if Grype saw a Go binary's main module package version was set to a string prefixed by `v0.0.0-`, it would **avoid any kind of vulnerability matching** for that package.
Meanwhile, Syft makes [several reasonable attempts](https://github.com/anchore/syft/blob/main/syft/pkg/cataloger/golang/parse_go_binary.go#L132-L149) to find a sane version to use as this main module's version. In the case of VCS information being embedded in the Go binary, Syft has enough information to produce a Go pseudoversion.
The "no vulnerability matching at all" approach may have been to avoid some false positive edge cases, or it may have predated some of the enhancements to Syft's version computation. But in any case, we were seeing this behavior result in false negatives, because many Go projects …
=> fix: use Go main module version when possible

cmd/grype/cli/commands/root.go, grype/match/ignore.go, grype/match/ignore_test.go
Follow up on #1787 for debian packages, not just rpms.
Adds ignore rules for indirect matches on "linux" upstream package if the binary package is the linux-headers-* or linux-libc-dev packages since those are just headers files not the code that has the linux source that is vulnerable.
=> fix: add linux and libc-dev headers ignore rules for debian packages

README.md, cmd/grype/cli/commands/root.go, cmd/grype/cli/options/match.go, grype/matcher/golang/matcher.go, grype/matcher/golang/matcher_test.go
Add a new config option for grype to NOT allow module comparison when there is a pseudo version and main module.
The default for this value is `true`, but users have the option to disable in case FP introductions are too high.
```
match:
golang:
using-cpes: false
always-use-cpe-for-stdlib: true
allow-main-module-pseudo-version-comparison: true
```
```
GRYPE_MATCH_GOLANG_ALLOW_MAIN_MODULE_PSEUDO_VERSION_COMPARISON
```
```
export GRYPE_MATCH_GOLANG_ALLOW_MAIN_MODULE_PSEUDO_VERSION_COMPARISON=true
syft -o json ollama/ollama:0.1.32 | go run cmd/grype/main.go
------
github.com/ollama/ollama    v0.0.0-20240414223325-7027f264fbb3  0.1.29             go-module  GHSA-5jx5-hqx5-2vrj  High
```
```
export GRYPE_MATCH_GOLANG_ALLOW_MAIN_MODULE_PSEUDO_VERSION_COMPARISON=false
syft -o json …
```
=> config: add config opt in golang pseudo version main module comparison 

README.md
- Adds data sources added since this list was last updated: Chainguard and Wolfi SecDBs
- Minor alphabetizing and case corrections
=> docs: update README with newer data sources

test/install/Makefile
Github recently updated their runners for osx to use arm64 architecture. The previous version of grype v0.24.0 did not support this release so our AC would fail. I've updated this test to an older version of grype, but one that adopts the arch used by the default GH runner.
=> fix: update grype version in ac tests to support darwin arm64

grype/presenter/sarif/presenter.go, grype/presenter/sarif/presenter_test.go, grype/presenter/sarif/test-fixtures/snapshot/TestSarifPresenter_image.golden
This PR adjusts the SARIF output to pass the Microsoft JS validator and adds a validation step to the unit tests.
Fixes: #1833
=> fix: update sarif to pass microsoft validator

grype/vulnerability_matcher.go, grype/vulnerability_matcher_test.go
The number of ignored matches was not being updated in the TUI, causing confusing numbers to be displayed. For example, scanning the `golang:latest` resulted in:
```
$ grype golang:latest -o json | jq '.matches | length'
✔ Scanned for vulnerabilities     [454 vulnerability matches]  
├── by severity: 1 critical, 35 high, 82 medium, 8 low, 231 negligible (97 unknown)
└── by status:   0 fixed, 454 not-fixed, 0 ignored 
297
```
With this fix, it now reads:
```
$ grype golang:latest -o json | jq '.matches | length'
✔ Scanned for vulnerabilities     [297 vulnerability matches]  
├── by severity: 1 critical, 35 high, 82 medium, 8 low, 231 negligible (97 unknown)
└── by status:   0 fixed, 454 not-fixed, 157 ignored 
297
```
Additionally, when using `--by-cve`, ignored matches were not being …
=> fix: update ignored vulnerability count in tui

grype/pkg/package.go, grype/pkg/package_test.go
Basically, when we're cataloging we remove some packages by ownership overlap, (e.g. if you're on redhat and do `yum install python3-urllib`, grype will drop the PyPI package `urllib` in favor of the RPM `python3-urllib`, because we have better match information for the distro package than for PyPI, e.g. because RedHad backported a fix to an old version of the python code or something).
We do this:
``` go
from, ok := r.From.(pkg.Package)
if ok && excludePackage(comprehensiveDistroFeed, p, from) {
continue
}
```
Which seems fine, _however_, some relationships have a From of type `*pkg.Package`, not type `pkg.Package` (pointer vs struct). This causes the type assertion in grype to _always_ fail, resulting FPs.
The underlying reason is that the syft scanner does this:
``` go
parent := …
```
=> fix: ask catalog for package, rather than type asserting

.github/workflows/release-version-file.yaml
Best practices for github workflows detail that top level permissions should be declarative `read`.
This PR updates the top level permissions for the `release-version-file` to `contents:read`
=> chore: add top level permissions to new workflow

cmd/grype/cli/cli.go, cmd/grype/cli/commands/completion.go, cmd/grype/cli/commands/db_check.go, cmd/grype/cli/commands/db_delete.go, cmd/grype/cli/commands/db_import.go, cmd/grype/cli/commands/db_list.go, cmd/grype/cli/commands/db_status.go, cmd/grype/cli/commands/explain.go, cmd/grype/cli/commands/util.go
We have a handful of commands that print out simple reports directly to stdout/stderr:
- `db status`
- `db check`
- `db import`
- `db list`
- `explain`
- `completion`
Without first disabling the TUI, which will put the terminal into raw mode, you may see artifacts in the terminal. This PR disables the TUI and allows for free-printing to the terminal on a per-command basis.
=> Disable TUI for simple commands

README.md, cmd/grype/cli/options/match.go
About 6 weeks ago, I opened https://github.com/anchore/grype/pull/1797 in an effort to **reduce false negatives** for the main modules of Go binaries. Before that PR, Grype's previous behavior was to avoid vulnerability matching for the main module altogether if the detected module version was prefixed with `v0.0.0-`. Grype's reasoning for this had been that Syft will manufacture pseudo versions that start with `v0.0.0-` in the case where it's not able to find a real version in the Go binary itself.
By making the change in the PR linked above, we indeed saw some reduction in false negatives 🎉 , which was great. We weren't sure about the larger impact of false positives. I only [speculated](https://github.com/anchore/grype/pull/1797#issuecomment-2052672419) about the potential effects:
>My …
=> fix: Go main module pseudo version matching: turn off by default

README.md
As described in [anchore#572](https://github.com/anchore/grype/issues/572) setting just the GRYPE_DB_CACHE_DIR environment variable doesn't successfully make grype use the custom cache location. TMPDIR needs to be set as well.
=> fix: add note about TMPDIR env var

.binny.yaml, test/integration/utils_test.go
When trouble shooting an issue in another PR https://github.com/hibare/grype/actions/runs/9402939074/job/25898220305 I found that there were utilities being referenced in legacy locations. It seems that skopeo was missed when porting the tool management approach and the cache was busted, revealing the issue:
```
task: [integration] go test -v ./test/integration
=== RUN   TestCompareSBOMInputToLibResults
utils_test.go:42: Cache miss for image anchore/test_images:vulnerabilities-alpine; copying to archive at /home/runner/work/grype/grype/test/integration/test-fixtures/cache/anchore-test_images-vulnerabilities-alpine.tar
utils_test.go:68: fork/exec /home/runner/work/grype/grype/.tmp/skopeo: no such file or directory
```
This PR adds skopeo as a managed tool and updates the test util code to …
=> Add skopeo to managed utilities

README.md
Docs  with new end points:
https://central.sonatype.org/consume/
URL - 
https://repo1.maven.org/maven2
Current url and response:
https://search.maven.org/solrsearch/select
Solr returned 400, msg:
=> Updating maven URLs in README.md

grype/match/matches_test.go, grype/match/sort.go
A common case in vulnerability matching is when two vulnerability matches are the same except for their location. I noticed this case was causing Grype to produce inconsistent output when using its match sorting, e.g. `sort.Sort(match.ByElements(matches))`.
This PR adds consideration for locations into the match sort ordering logic.
=> fix match sort ordering for different locations

grype/match/sort.go
This is a follow-up to #1944. Using `String()` works _mostly_ for sorting, but I expected `String()` to return a simple filepath, and instead it returns a funky string like: `Location<id=72 RealPath="usr/lib/go/pkg/tool/linux_amd64/buildid">`. 
This causes issues because the `id=<...>` value will be sorted lexically, and more than that, it looks like for most paths in Syft, this `id` value is controlled by an auto-incrementing global variable, so its value will vary quite widely across different execution contexts.
(I'm not sure if anything is depending on this kind of `Location< .... >` string value... If not, it could potentially be worth considering changing `String()` to return the RealPath or AccessPath to be friendlier to library consumers.)
This PR updates the sorting logic to use …
=> fix: use location `RealPath` not `String()` for match sorting

.github/actions/bootstrap/action.yaml, .github/dependabot.yaml
Allows dependabot to also keep the boostrap action updated
=> chore: enable dependabot to keep boostrap action updated

Taskfile.yaml, test/quality/Makefile
Our `TEST_DB` for the quality gate was very far behind our most recent build.
This patch unblocks our CI for other current pull requests.
I think keeping the target pinned here still makes sense, but maybe 5/6 months is too large a window? Happy to hear others thoughts on the way it should be.
=> chore: update test_db_url

cmd/grype/cli/commands/db_status.go
The UI is being disabled after the run instead of before the run, leading to garbled output:
```
❯ grype db status
Location:  /Users/wagoodman/Library/Caches/grype/db/5
Built:     2024-07-24 01:31:07 +0000 UTC
Schema:    5
Checksum:  sha256:e56b36edcd25dcff0566eecb2b83fad05e5451d881b81662d9b16f903185b235
Status:    valid
```
This PR fixes this behavior
=> Disable ui before run function on db status

.github/scripts/trigger-release.sh
This PR adjusts the release workflow to use the `.tool/gh` instead of relying on a `gh` in the path as well as defaulting the GITHUB_TOKEN based on a `gh auth login`.
Note: I used this version of the script to successfully release: https://github.com/anchore/grype/releases/tag/v0.79.4
=> chore: update release script to use gh from binny

cmd/grype/cli/commands/root.go, cmd/grype/cli/commands/update.go, cmd/grype/cli/commands/update_test.go
In order to better understand which versions of grype are in use, this PR just adds a `User-Agent` header that is set when grype checks for updates, which only includes the application name and version. This behavior matches [what Syft is doing](https://github.com/anchore/syft/blob/a4b5dcd0df80f6a58c8610e25104647710c1da5d/cmd/syft/internal/commands/update.go#L97).
=> chore: add grype version to application update check headers

cmd/grype/cli/options/database.go
Depending on region and network conditions, 120s was not enough time for many clients, leading to some complaints. Raise the default timeout to five minutes.
There's an open question whether we should wait for more data from the [latest attempt to resolve the CDN issues](https://anchorecommunity.discourse.group/t/grype-db-network-and-cdn-issues/48/4?u=willmurphy)
Fixes https://github.com/anchore/grype/issues/1885
=> fix: higher default timeout for database download

test/quality/Makefile
Since we lowered the number of days in the database listing file, it causes an issue in the quality tests here, since the Makefile validates the database exists in the listing file and would require updating the database URL quite frequently. This PR just removes the pseudo-age-check since we're already updating this every month with an automated workflow.
=> chore: remove quality gate Makefile db age check

grype/db/vulnerability_provider.go, grype/db/vulnerability_provider_mocks_test.go, grype/db/vulnerability_provider_test.go
Fixes #2048
Today when we are fetching a entry from the DB we will raise up failures when attempting to craft vulnerability objects all the way back up through the matcher. This is not correct behavior since there may have been matched we could have raised up but did not. Instead we should be logging warnings when this occurs (since it affects the results of the report, even if it's not actionable) and still allow for other matches to be made.
=> Do not fail when inflating DB records

grype/distro/type.go, grype/matcher/apk/matcher.go, grype/matcher/apk/matcher_test.go
Even if there are vulnerability scan results for search.ByPackageDistro in apk matcher, if the SBOM does not have a CPE set, the results are ignored and the vulnerability search result becomes empty.
resolves #2039
And amazon Inspector sbom generator genereta this component.
```
{
"bom-ref": "comp-2",
"type": "operating-system",
"name": "Alpine Linux",
"version": "3.17.1"
}
```
To make grype recognize this file as Alpine, you need to add the following entry to grype/distro/type.go:
`
"Alpine Linux":  Alpine,
`
=> Add "Alpine Linux" to IDMapping; handle no CPEs error in findApkPackage.

templates/junit.tmpl
Fixes broken XML for description like "ruby < 3.0" by html escaping the text.
=> Escape description in junit.tmpl

.binny.yaml, .github/actions/bootstrap/action.yaml, go.mod, go.sum
Note: we were consuming 1.22.6, but this get's us further upstream for any future security fixes filed against 1.22.x which would require a 1.23 update
Runc was updated as a precaution but the vuln in question was withdrawn:
https://github.com/advisories/GHSA-c5pj-mqfh-rvc3
=> chore(sec): update Golang and runc to latest releases

.gitmodules
Fixes #2100  - we should not use git protocol URIs for modules as it can be problematic for consumers behind restrictive or poorly configured proxies.
=> fix: Update gitmodule url

grype/matcher/apk/matcher.go, grype/matcher/apk/matcher_test.go
This fixes a bug in Grype's APK matching logic (affecting Alpine and Wolfi) where if there was an NVD match to a package, Grype wasn't doing the resolution-to-origin-package to find relevant data in the secdb for the match. This created a case where Grype would show a distro package as vulnerable even though the distro had marked the package as fixed or a false positive already.
This PR adds the missing check to the matcher and adds a unit test to cover this case.
=> fix(apk): find secdb entries for origin packages

grype/db/curator.go, grype/load_vulnerability_db_bench_test.go
Fixes #1502
This PR aims to improve the performance of `LoadVulnerabilityDB` when `ValidateByHashOnGet` is set to `true`
As described in the linked issue, `GetStore` and `Status` both hash the db. This PR changes `Status` to not hash the db by removing the call to `c.Validate`
As far as I can tell, `Status` is only used in a few places:
1. `LoadVulnerabilityDB`
This should not be an issue since `GetStore` already hashes the db
https://github.com/anchore/grype/blob/e7ceffadc856ce70b2854eefa3fc78f8770365e7/grype/load_vulnerability_db.go#L28
1. `runDBStatus`
I am unsure whether hashing the db is desired behavior for `grype db status`. If so, perhaps a new field could be added to `db.Config` to allow CLI and library users to configure this behavior? …
=> fix: hash vuln db only once on load

cmd/grype/cli/commands/db_check.go, cmd/grype/cli/commands/db_update.go, cmd/grype/cli/options/database.go, go.mod, grype/db/legacy/distribution/curator.go, grype/db/legacy/distribution/curator_test.go, grype/load_vulnerability_db.go, test/cli/db_validations_test.go
Currently grype will always reach out to check if there is a DB update, even if grype is run several times with in a short period of time. In reality we're only updating the DB once a day at this time, so checking for an update this frequently is fairly wasteful both client-wise and on the CDN.
This change adds a new `update-check-max-frequency` with a default of 2 hours. This only affects the scan path and not `db check` and `db update` paths.
This will also have the added value of reducing traffic spikes when we publish new databases, assuming most clients are not explicitly running `db update`.
=> Add low pass filter to DB update checks

go.mod, go.sum, internal/file/getter.go, internal/file/tar_xz_decompressor.go, internal/file/tar_xz_decompressor_test.go, internal/file/xz_decompressor.go, internal/file/xz_decompressor_test.go
Moving from github.com/ulikunitz/xz to github.com/xi2/xz saves upwards of half the time when decompressing archives on download. This PR is the spiritual mirror to https://github.com/hashicorp/go-getter/pull/262 , which was never merged and closed for some reason.
Partially addresses https://github.com/anchore/grype-db/issues/367
=> Use faster xz lib for decompression

templates/html.tmpl
Should be a space between "Name:" and "container:tag" currently that doesn't render, so adding a space here fixes that.  Tested on Firefox
=> Add a space following the "Name:" label in html.tmpl

grype/search/only_vulnerable_targets.go, grype/search/only_vulnerable_targets_test.go
Removed `wordpress` from `known` targets due to wordpress cataloger support (https://github.com/anchore/syft/pull/2218) in `Syft`
=> feat: wordpress-plugin support

grype/db/internal/gormadapter/open.go, grype/db/internal/gormadapter/open_test.go, grype/db/v1/store/store.go, grype/db/v2/store/store.go, grype/db/v3/store/store.go, grype/db/v4/store/store.go, grype/db/v5/store/store.go, grype/db/v6/db.go, grype/db/v6/db_metadata_store.go, grype/db/v6/db_metadata_store_test.go, grype/db/v6/models.go, grype/db/v6/store.go
Partial implementation for #2128 and #2132 in terms of the `DBMetadata` object
Adds:
- the `DBMetadata` table for v6
- the store reader and writer implementation
=> Add v6 DB metadata store

grype/matcher/apk/matcher.go, grype/matcher/apk/matcher_test.go
This is to address false fixed ins in Alpine, Chainguard, or Wolfi that might be introduced by anchore/grype-db#112.
=> fix: use fix info from secDB in APK matcher even if NVD fix info present

README.md
This follows the same pattern as the other badges at the top of the readme. It adds the mastodon link to the Grype account.
This also means that the link back here from the Mastodon account's profile page will show as 'Validated' once it lands, which gives the account more authenticity.
I also converted all the links to html from markdown format so that I could add the necessary `rel="me"` required by mastodon validation.
=> [chore] Add mastodon link to README.md

grype/search/cpe_test.go, grype/search/only_vulnerable_targets.go
=> fix: exclude binary packages from CPE target software component filter logic

test/quality/.yardstick.yaml
Should merge after https://github.com/anchore/vulnerability-match-labels/pull/138
=> chore: bump syft in quality gate to v1.14.0

cmd/grype/cli/commands/root.go, cmd/grype/cli/commands/root_test.go, grype/matcher/apk/matcher_test.go, grype/search/cpe.go, grype/search/cpe_test.go, grype/search/distro.go, grype/search/distro_test.go, grype/search/language.go, grype/search/language_test.go, grype/vulnerability_matcher_test.go
As discussed on [discourse](https://anchorecommunity.discourse.group/t/grype-reporting-vulns-for-unknown-versions/174/5), grype should not be searching for packages that are missing version information as these will always yield incorrect results.
Additionally while working on this it was found that searched CPE versions were not always being raised accurately (when being overridden) -- this PR additionally fixes this behavior.
=> Skip matching on packages with missing version info

grype/pkg/package.go
azurelinux should be considered as providing a comprehensive vulnerability data source
=> fix: azurelinux considered as comprehensive distro

cmd/grype/cli/cli.go, cmd/grype/cli/commands/util.go, go.mod, go.sum, test/cli/config_test.go, test/cli/test-fixtures/configs/dir1/.grype.yaml, test/cli/test-fixtures/configs/dir2/.grype.yaml
This PR introduces changes to the configuration loading to support hierarchical configuration (loading local `.grype.yaml`, and a global `~/.grype.yaml`, for example), support for multiple configuration files (using multiple `-c` flags, etc.), and _configuration profiles_.
Fixes: #2009
=> feat: multi-level configuration and profiles

README.md
This PR updates the documentation to remove the erroneous grype db cache dir value, which resulted in an unexpected location on the filesystem: `./$XDG_CACHE_DIR`.
Fixes #2206
=> docs: update config section to be valid

cmd/grype/cli/commands/db_diff.go, cmd/grype/cli/commands/db_list.go, cmd/grype/cli/commands/db_providers.go, cmd/grype/cli/commands/db_providers_test.go, cmd/grype/cli/commands/db_search.go, internal/constants.go
resolves #2131 
- Provider data is read from `provider-metadata.json` file.
- Added flag `-o`/`--output` flags which accept `json` and `table`.
- Display logic is separate from the provider data collection. 
- Can be easily updated for db schema `v6`.
- Fails gracefully, with relevant error message, for absence of `provider-metadata.json` file.
- Updated `Readme.md` for the new command.
=> Add `grype db providers` command

test/integration/match_by_image_test.go
Based on https://github.com/anchore/grype/issues/744#issuecomment-2448163737 we still have more work to do before we can claim completion on gentoo support. This was revealed by a fix made in #2226 .
=> Remove gentoo integration test

grype/db/v6/db.go, grype/db/v6/models.go, grype/db/v6/provider_store.go, grype/db/v6/provider_store_test.go, grype/db/v6/store.go
Adds the provider model and store accessor to the DB v6 package and schema.
The design originally called for two additional fields that were left out:
- `InstanceCacheURL`: there is no guarantee that the data used to build the DB is from a cache, which would make this field not dependable 
- `SourceURL`: vunnel is the source of truth for this information
Partially implements #2128 and #2132
=> Add v6 provider store

README.md
This clarifies the license under which the Grype "alien" logo is released. This is necessary to enable us to share the logo in certain online communities.
=> doc: Add official Grype logo license information

grype/match/details.go, grype/match/details_test.go, grype/match/fingerprint.go, grype/match/match.go, grype/match/match_test.go, grype/match/matches.go, grype/match/matches_test.go, grype/match/type.go, grype/vulnerability/vulnerability.go, grype/vulnerability_matcher_test.go, test/integration/match_by_image_test.go
Today if a vulnerability is matched for an artifact both directly and indirectly (using a source/origin package instead of the downstream/original package) then we raise up both matches separately:
```
$ grype 'pkg:rpm/ol/perl-Errno@1.28-417.el8_3?arch=x86_64&epoch=0&upstream=perl-5.26.3-417.el8_3.src.rpm&distro=ol-8.3' -q -o json | jq '.matches[] | select(.artifact.name == "perl-Errno" and .vulnerability.id == "ELSA-2021-1678") | .matchDetails'
```
```json
[
{
"type": "exact-direct-match",
"matcher": "rpm-matcher",
"searchedBy": {
"distro": {
"type": "oraclelinux",
"version": "8.3"
},
"namespace": "oracle:distro:oraclelinux:8",
"package": {
"name": "perl-Errno",
"version": "0:1.28-417.el8_3"
}
},
"found": {
"versionConstraint": "< 0:1.28-419.el8 (rpm)",
"vulnerabilityID": …
```
=> Merge indirect matches with direct matches

cmd/grype/internal/ui/ui.go
This restores the UI on teardown (note that it is redirected to a buffer on setup). This will now show logging events after the UI has returned screen control.
=> Restore log on UI teardown

go.mod, grype/db/internal/schemaver/schema_ver.go, grype/db/internal/schemaver/schema_ver_test.go, grype/db/v6/description.go, grype/db/v6/description_test.go, grype/db/v6/distribution/client.go, grype/db/v6/distribution/client_test.go, grype/db/v6/distribution/latest.go, grype/db/v6/distribution/latest_test.go, grype/db/v6/distribution/status.go
Adds a new `distribution.Client` (for v6) responsible for:
- fetching a `latest.json` file
- determining if a given existing DB description is older or newer than a candidate update
- downloads candidate DB archives into a given directory, automatically failing if an expected archive checksum differs
One benefit of this approach is that the client is unaware of any installation concerns.
Partially implements #2125
=> Add v6 distribution client

go.mod, grype/db/internal/gormadapter/open.go, grype/db/internal/gormadapter/open_test.go, grype/db/v6/blob_store.go, grype/db/v6/blob_store_test.go, grype/db/v6/blobs.go, grype/db/v6/db.go, grype/db/v6/models.go, grype/db/v6/store.go, grype/db/v6/vulnerability_store.go, grype/db/v6/vulnerability_store_test.go
Adds the `VulnerabilityHandle`, `Blob`, and `BlobDigest` models as well as the first blob, `VulnerabilityBlob` with supporting structs and store accessors (only in the Db v6 schema). 
When adding a new vulnerability to the DB the store objects handle serializing the object to JSON and storing to the DB within the `blobs` table (and the same is true for fetching in reverse). When the store is open for writing the `blob_digests` table is created and populated with each write to the `blobs` table; since this takes up a good amount of space in the DB and isn't needed for distribution, upon closing the store this table is dropped entirely.
Partially addresses #2128 #2132
=> Add v6 vulnerability & blob stores

grype/db/v6/affected_package_store.go, grype/db/v6/affected_package_store_test.go, grype/db/v6/blobs.go, grype/db/v6/db.go, grype/db/v6/enumerations.go, grype/db/v6/enumerations_test.go, grype/db/v6/models.go, grype/db/v6/store.go, grype/db/v6/vulnerability_store.go
Adds the following V6 schema models:
- `AffectedPackageHandle`
- `Package`
- `OperatingSystem`
Adds the following blobs (including supporting structs):
- `AffectedPackageBlob`
- `AffectedRange`
- `Fix`
- `FixDetail`
- `AffectedVersion`
The store has been updated to reflect the additional getters/setters for these objects.
Additional changes made:
- added parser functions + tests for enums (`VulnerabilityStatus`, `FixStatus`,  and `SeverityScheme`)
Partially addresses  #2132
Partially addresses #2128
=> Add AffectedPackage store

grype/db/v6/affected_package_store_test.go, grype/db/v6/blob_store_test.go, grype/db/v6/db.go, grype/db/v6/db_metadata_store_test.go, grype/db/v6/description.go, grype/db/v6/description_test.go, grype/db/v6/distribution/client.go, grype/db/v6/installation/curator.go, grype/db/v6/installation/curator_test.go, grype/db/v6/internal/db.go, grype/db/v6/models.go, grype/db/v6/provider_store_test.go, grype/db/v6/status.go, grype/db/v6/store.go, grype/db/v6/vulnerability_store_test.go, internal/file/hasher.go
Adds in a new DB curator for v6, which is responsible for:
- using the new `distribution.Client` to facilitate validated updates of the DB
- provide read-access to the DB
- facilitate other management concerns (import, delete, status)
Partially implements #2125
=> Add v6 DB curator

grype/db/v6/affected_package_store.go, grype/db/v6/affected_package_store_test.go, grype/db/v6/models.go, grype/db/v6/models_test.go
Today we have a few hard coded elements that affect which namespace is selected for given distro information:
- debian unstable: look for indications of [`sid` in the pretty-name](https://github.com/anchore/grype/blob/52e21b88c9ece087f25c5ec44d7f0fdb9fb173c8/grype/distro/distro.go#L60) then explicitly set the version to `unstable` which is [acted upon downstream](https://github.com/anchore/grype/blob/52e21b88c9ece087f25c5ec44d7f0fdb9fb173c8/grype/db/v5/namespace/index.go#L120-L124) to map to `sid` vulnerability data
- rolling versions: [manually list](https://github.com/anchore/grype/blob/52e21b88c9ece087f25c5ec44d7f0fdb9fb173c8/grype/distro/distro.go#L98) which distros via code that should match against a [single vulnerability stream](https://github.com/anchore/grype/blob/52e21b88c9ece087 …
=> Add data-driven approach to v6 distro search

README.md
This moves the supported grype range from v0.40.1 to v.51.0 (so we support v5+).
Related to #2286
=> Move supported grype version to only v5+

grype/db/v6/distribution/client.go, grype/db/v6/distribution/client_test.go, grype/db/v6/installation/curator.go, grype/db/v6/installation/curator_test.go
There are a few assumptions made by the v6 curator surrounding DB directory existence. This PR fixes activation-related issues with the DB not existing.
=> Fix DB v6 curator directory creation

grype/db/v6/affected_cpe_store_test.go, grype/db/v6/affected_package_store.go, grype/db/v6/affected_package_store_test.go, grype/db/v6/models.go
This PR allows for direct associations of `Packages` to `CPEs` so that raising up more accurate `AffectedPackageHandles` over `AffectedCPEHandles` is possible. The data enrichment process we apply to the NVD data today will be leveraging this functionality (which lands when a new vunnel provider is written). This also makes the nomenclature correction of renaming `cpe.Type` to `cpe.Part`.
=> Add ability to map CPEs directly to packages (v6 schema)

cmd/grype/cli/commands/db_search.go, grype/db/v6/affected_cpe_store.go, grype/db/v6/affected_cpe_store_test.go, grype/db/v6/affected_package_store.go, grype/db/v6/affected_package_store_test.go, grype/db/v6/blobs.go, grype/db/v6/db.go, grype/db/v6/models.go, grype/db/v6/provider_store.go, grype/db/v6/provider_store_test.go, grype/db/v6/vulnerability_store.go, grype/db/v6/vulnerability_store_test.go
Updating the v6 vulnerability handle model to be able to search by:
- published date
- modified date
- withdrawn date
- status
One impact of this change is that distribution archives are now ~5 MB larger than before this PR.
In the same vein as #2297 , this makes the vulnerability store have only a single getter and parameterizes all search possibilities.
This PR also adjusts the following behavior:
- when adding vulnerabilities via the store we ensure that all records with publication dates have a modification date as well.
- provider information to only be written with vulnerability records. This makes it more difficult to write a vuln entry without a provider or vice versa. For this reason all adder methods on the provider store were removed.
- migrates code for affected* store input …
=> Migrate searchable vulnerability data out of v6 blob

grype/db/v6/distribution/client.go, grype/db/v6/distribution/latest.go, grype/db/v6/distribution/latest_test.go
Noticed odd output with v6 experiment enabled when running `db check`:
From a testing perspective there is good coverage for functionality, however, the logging lines were flipped (in the wrong conditions).
It was also found that getting a latest doc from a reader wasn't allowing for there to be no update (indicated as nil in testing currently).
This PR fixes this behavior:
=> `latest.json` from reader should allow for empty values

grype/db/v6/affected_package_store_test.go, grype/db/v6/models.go, grype/db/v6/store.go
This ports the [logic that controls which namespace](https://github.com/anchore/grype/blob/v0.85.0/grype/db/v5/namespace/index.go) to use when searching for matches in v5 to v6. Specifically, v6 is a data-driven approach, however, only the schema and [store has been updated](https://github.com/anchore/grype/blob/0699f8434242998a79578651b39ca15e6a3f721c/grype/db/v6/affected_package_store.go#L279-L284), no data has been hydrated so that it can be used in matching --this PR hydrates the lookup table. 
Q: Why not plumb this in through vunnel? 
A: We may do that one day, but it's not necessary to do that today. 
Q: Wait -- you said data-driven, but this code change is in grype... wouldn't this require a code change to add/modify these aliases, thus entirely defeating the point of making it …
=> Add initial os aliases to the DB after DB v6 migration

grype/db/v6/vulnerability_store.go, grype/db/v6/vulnerability_store_test.go
Today when writing vulns to the store there may be duplciates:
```
CVE-2020-13956  debian                                                                            
CVE-2020-13956  debian                                                                            
CVE-2020-13956  debian                                                                            
CVE-2020-13956  debian                                                                            
CVE-2020-13956  debian      medium                                                                
CVE-2020-13956  debian                 
```
From an affected-packages perspective this is what is happening:
```
CVE-2020-13956  httpcomponents-client                                                                      deb …
```
=> v6 deduplicate vulnerabilities when adding to DB

README.md
Just noticed the link was broken -- upstream changed the URL :sweat_smile: 
Hope it helps!
=> Fix broken link to cosign documentation

grype/db/internal/gormadapter/logger.go, grype/db/internal/gormadapter/open.go, grype/db/v6/affected_cpe_store.go, grype/db/v6/affected_package_store.go, grype/db/v6/affected_package_store_test.go, grype/db/v6/blob_store.go, grype/db/v6/blobs.go, grype/db/v6/db.go, grype/db/v6/installation/curator.go, grype/db/v6/models.go, grype/db/v6/vulnerability_store.go, grype/db/v6/vulnerability_store_test.go
Today the v6 store can search for singular things (a single vulnerability, filter by a single distro, search by a single package). This PR changes the store to support searching and filtering by multiple criteria (supporting https://github.com/anchore/grype/pull/2303).
All changes made:
- add slice of all `*Spec` objects in searching
- allow for configurable limit on queries (default is no limit)
- fetch and attach blobs in batches (not individually)
- fetch all queries in small batches (better support for queries with several results)
- adjust indexes:
- hydrate them when opening a writable DB without truncate options
- adds additional individual indexes for common search cases (search by name, product, or vendor)
- fix logging and monitor values when importing/downloading a DB
- better …
=> Allow v6 store to support multiple qualifiers

grype/db/v6/description.go, grype/db/v6/installation/curator.go
Note when starting with no state and updating the DB there is a warning:
This PR adjusts the behavior such that this common case does not warn:
=> (DBv6) Do not warn if DB missing when updating

grype/db/v6/affected_package_store.go, grype/db/v6/affected_package_store_test.go, grype/db/v6/models.go, grype/db/v6/models_test.go
It is common to users to input "oracle" or "oraclelinux" instead of "ol", which is the release ID as found in /etc/os-release. This makes it easier to find the correct OS given a fuzzy name.
=> Have aliases for non standard names in DB v6 schema

cmd/grype/cli/commands/db_check.go, cmd/grype/cli/commands/db_delete.go, cmd/grype/cli/commands/db_diff.go, cmd/grype/cli/commands/db_import.go, cmd/grype/cli/commands/db_list.go, cmd/grype/cli/commands/db_providers.go, cmd/grype/cli/commands/db_search.go, cmd/grype/cli/commands/db_status.go, cmd/grype/cli/commands/db_update.go, cmd/grype/cli/commands/explain.go
Today we use the options structs from each command registered with clio to build the output of the `grype config` command. However, not all commands are meant to support options being configured via a config file -- but these are being shown in the `grype config` output anyway:
```
diff /tmp/og-config /tmp/new-config
```
```diff
228,236d227
< 
< # delete downloaded databases after diff occurs (env: GRYPE_DELETE)
< delete: false
< 
< # format to display results (available=[table, json]) (env: GRYPE_OUTPUT)
< Output: 'table'
< 
< # CVE IDs to explain (env: GRYPE_CVE_IDS)
< cve-ids: []
```
Note that `Output` is for `grype db *` commands and there is still an `output` value documented in the `grype config` output.
This PR removes all subcommands from consideration when generating `grype …
=> Clean up config help text

grype/db/v6/affected_package_store_test.go, grype/db/v6/models.go
This was an oversight in a previous PR -- enum types like this should be referenced in the table types if they are ultimately string types.
=> Use v6 vulnerability status enum

cmd/grype/cli/commands/internal/dbsearch/affected_packages.go, cmd/grype/cli/commands/internal/dbsearch/affected_packages_test.go, grype/db/v6/affected_cpe_store_test.go, grype/db/v6/affected_package_store.go, grype/db/v6/affected_package_store_test.go, grype/db/v6/data.go, grype/db/v6/models.go, grype/db/v6/store.go, grype/db/v6/vulnerability_store.go
This adds the capability to search for package specifier ecosystem aliases, such as translating purl types to known syft package types, to ensure we're searching for the best ecosystem values relative to what's in the DB.
This PR also:
- renames the package.type field to package.ecosystem
- adds case insensitivity to commonly searched fields.
=> Add package spec alias + case insensitivity for v6 DBs

test/quality/.yardstick.yaml
Docker no longer seems to load V1-formatted images and quality gates are failing due to this. As a temporary fix, I've just removed all the v1-format images from the quality gate until they can be replaced with working ones.
=> chore: disable v1 images in quality tests

grype/db/v6/db.go
This removes the sql debug statements when trace logging when using the v6 exp feature flag. This has no impact on debugging/logging for v1-5 DBs.
=> Remove db debug statements for v6

.github/dependabot.yaml
Fixes a typo in the dependabot config which was preventing automated updates to the composite bootstrap action definition.
=> chore(ci): fix composite GitHub action path in dependabot config

cmd/grype/cli/commands/internal/dbsearch/affected_packages.go, grype/db/internal/gormadapter/open.go, grype/db/internal/gormadapter/open_test.go, grype/db/v6/affected_cpe_store.go, grype/db/v6/affected_cpe_store_test.go, grype/db/v6/affected_package_store.go, grype/db/v6/affected_package_store_test.go, grype/db/v6/blob_store.go, grype/db/v6/blob_store_test.go, grype/db/v6/blobs.go, grype/db/v6/cache.go, grype/db/v6/cache_test.go, grype/db/v6/db.go, grype/db/v6/models.go, grype/db/v6/provider_store_test.go, grype/db/v6/store.go, grype/db/v6/store_test.go, grype/db/v6/vulnerability_store.go, grype/db/v6/vulnerability_store_test.go, schema/grype/db-search/json/schema-1.0.0.json, schema/grype/db-search/json/schema-latest.json
All changes on this PR are purely to decrease the time it takes to build a v6 DB, which when incorporated the build time in CI drops from ~2.5 hours to ~25 minutes 🎉
Changes:
- add in-memory ID lookup for common or expensive models (e.g. CPEs originally had a large where clause to fetch similar rows, now this is an O(1) map lookup based on a string). This has been applied to CPEs, OperatingSystems, VulnerabilityHandles, Packages, and Providers. These are relatively flat records and based on debug logs appear to have a high cache hit rate. This also required ensuring we are correctly using this cache across transactions as well as within a transaction (deduplicating in memory).
- Minimizing use of any queries to the DB within `BeforeCreate` hooks
- keep blob digests in memory, not to a …
=> Performance enhancements for DB v6 writes

README.md, cmd/grype/cli/options/datasources.go, grype/db/v5/matcher/java/matcher.go, grype/db/v5/matcher/java/maven_search.go, grype/db/v5/matcher/java/maven_test.go
Allow overriding the default 300ms rate limit for maven API requests via config. This helps users tune request rates based on their specific environment and maven server capacity/restrictions.
Example config:
```yaml
external-sources:
maven:
rate-limit: 400ms # or lower than the default if users prefer
```
This PR also includes:
- addition of unit test for the new configurable rate limits
- removal of single unit test case, testing default config as unnecessary given the `defaultExternalSources`
- doc updates for new config, also updated the base maven URL in the docs to match what is being used
- small fix to warn logging, if `no artifact is found`, we don't want to log a warning
=> external-sources: make maven rate limit configurable

grype/db/v6/enumerations.go
This will be used in grype-db when transforming OS related records with advisories (so they are explicitly tagged)
=> Add advisory tag constant

grype/matcher/internal/cpe_test.go, grype/matcher/internal/only_vulnerable_targets.go
=> fix: exclude unknown packages from CPE target software component filter logic

grype/vulnerability_matcher.go
During v6 refactoring, there was a small change made incorrectly to how errors were returned from matchers. This PR corrects this issue.
=> fix: only log matcher errors

grype/db/v6/data.go
This enables `ByLanguage` based lookups in v6 DB schema to be data driven (without this there will be missing matches from the github provider).
=> Add language mapping to knpwn package specifier overrides (v6)

grype/db/v6/data.go
Currently jenkins plugins are stored within the java ecosystem within v6 DBs -- this adds a package specifier override to account for this.
=> Fix jenkins plugin matching for v6 DB schema

grype/internal/packagemetadata/discover_type_names.go, grype/pkg/cpe_provider.go, grype/pkg/cpe_provider_test.go, grype/pkg/provider.go, grype/pkg/purl_provider.go, grype/presenter/models/source.go, grype/presenter/models/source_test.go
This PR adjusts input processing for grype to allow for CPE literals from the CLI (in the same way PURLs are supported today):
```
grype 'cpe:2.3:a:zohocorp:manageengine_desktop_central:11'
✔ Scanned for vulnerabilities     [0 vulnerability matches]  
├── by severity: 4 critical, 0 high, 0 medium, 0 low, 0 negligible
└── by status:   3 fixed, 1 not-fixed, 0 ignored 
NAME                          INSTALLED  FIXED-IN    TYPE  VULNERABILITY   SEVERITY 
manageengine_desktop_central  11         2020-03-07        CVE-2020-8540   Critical  
manageengine_desktop_central  11         100251            CVE-2018-11717  Critical  
manageengine_desktop_central  11         100230            CVE-2018-11716  Critical  
manageengine_desktop_central  11                           CVE-2017-7213   Critical
``` …
=> Add CPE provider

grype/db/v6/db.go, grype/db/v6/db_metadata_store.go, grype/db/v6/db_metadata_store_test.go, grype/db/v6/installation/curator_test.go, grype/db/v6/models.go, grype/db/v6/vulnerability_decorator_store.go, grype/db/v6/vulnerability_provider.go, grype/presenter/models/vulnerability_metadata.go, grype/vulnerability/metadata.go
Adds EPSS scores to the JSON output on each vulnerability record. Note: this does not affect the sorting of the table yet, which will be done when KEV and EPSS are incorporated.
Partially addresses https://github.com/anchore/grype/issues/1973
=> Add EPSS models to the v6 DB

grype/version/golang_version.go, grype/version/golang_version_test.go
go1.24.0 stamps versions with `+incompatible+dirty` which is an
invalid SemVer version. Add a fixup to correct this to SemVer
compliant buildinfo version of `+incompatible.dirty` with a test case.
Related:
- https://github.com/golang/go/issues/71971
- https://github.com/anchore/grype/issues/2482
```
$ ./mygrype ../docker/mydocker | grep docker/docker
✔ Indexed file system                                                                                                                 ../docker/mydocker 
✔ Cataloged contents                                                                    7c98bb9a0a89d26031d23927b57f88cbbf2f326491f10500c9481bc907c011d4 
├── ✔ Packages                        [174 packages]  
├── ✔ File digests                    [1 files]  
├── ✔ File metadata …
```
=> version: add golang 1.24 version fixup

grype/db/v6/vulnerability_provider.go, grype/db/v6/vulnerability_provider_test.go
Relax query by CPE constraints to allow queries by product with no vendor specified
=> fix: allow querying for CPE with only vendor or product

grype/matcher/java/matcher.go, grype/matcher/java/matcher_mocks_test.go, grype/matcher/java/matcher_test.go
Following on to #2384 — this makes the failure mode return an error, in addition to logging the issue.
The motivation for this is that otherwise, the unreliability of scan results caused by Maven's rate limiting can't be noticed in programmatic contexts — only by studying log messages.
This adjusts the logic such that if the user wants to use Maven searching to affect vuln matching results, and this is unable to happen successfully, an error is returned indicating as much, which can then prompt the user explicitly to change their approach, such as by turning off the search or adjusting the self rate limiting time.
cc: @rawlingsj @wagoodman
=> fix(java): error out on maven search rate limiting

grype/db/v6/vulnerability.go, grype/db/v6/vulnerability_test.go
Updates the namespace generation logic to consider:
- mariner/azurelinux ID overrides should be more resilient when matching on version 1 & 2
- ubuntu should left pad minor versions with `0` (e.g. `ubuntu:distro:ubuntu:19.04` not `ubuntu:distro:ubuntu:19.4`)
=> Cover mariner and ubuntu namespace conversion

grype/db/v6/vulnerability.go, grype/db/v6/vulnerability_provider.go, grype/matcher/apk/matcher.go, grype/matcher/internal/cpe.go, grype/matcher/internal/distro.go, grype/matcher/internal/language.go, test/integration/match_by_image_test.go
Today vulnerability objects are being duplicated for each element in a version range (introduced in the v6 schema development), this PR restores the original behavior in grype so that all version ranges within a vulnerability are still associated with that single vulnerability.
Before this change (we're filtering down to what is affected relative to the given package):
```
openjdk             17.0.13+11                17.0.14                  binary  CVE-2025-21502  Medium     
```
Also before this change, but tweaking the code to show how many matches get created when you ignore this filtering behavior and create vulnerabilities for all of them:
```
openjdk             17.0.13+11                1.8.0_441                binary  CVE-2025-21502  Medium      
openjdk             17.0.13+11 …
```
=> Enumerate version ranges within a single match (don't duplicate)

test/quality/.grype.yaml, test/quality/.yardstick.yaml
Now that v6 schema has been released we can go back to using pinned DBs for the quality gate (since both sides of the comparison are using the same DB, where during v6 development this was not true). We also no longer need to ignore the CVE-2012-0979 and CVE-2019-5736 records from quality gate results they will now be part of the baseline comparison (since there was a new release).
=> Remove v6 development configuration

grype/db/v6/distribution/client.go, grype/db/v6/distribution/client_test.go, grype/db/v6/distribution/latest.go
Before v0.88.0 release of grype you could specify a listing file on the local filesystem:
```
$ curl -fsSLO "https://grype.anchore.io/databases/listing.json"
$ export GRYPE_DB_UPDATE_URL=${PWD}/listing.json
$ grype db check
```
However with the release of v0.88.0 this stopped working:
```
$ curl -fsSLO "https://grype.anchore.io/databases/v6/latest.json"
$ export GRYPE_DB_UPDATE_URL=${PWD}/latest.json
$ grype db check
[0000] ERROR unable to check for vulnerability database update: check for vulnerability database update failed: unable to fetch latest.json: Get "file:///tmp/scratch/latest.json": unsupported protocol scheme ""
```
(same is true with the `file://` scheme)
This PR fixes this behavior, allowing for an assumed local path (no scheme) and an explicit `file` scheme.
Fixes #2507
=> Allow for reading listing from local FS

grype/db/v6/vulnerability.go, grype/db/v6/vulnerability_test.go
This PR corrects an issue where the `relatedVulnerabilites` field was being populated with a record for the same vulnerability.
Fixes: #2514
=> fix: exclude self from related vulnerability list

cmd/grype/cli/commands/db_import.go, grype/db/v6/distribution/client.go, grype/db/v6/distribution/client_test.go, grype/db/v6/installation/curator.go, grype/db/v6/installation/curator_test.go
Enables being able to import DBs from a URL (whereas today this must be a local file), so the user does not need to download them first:
```
$ grype db import https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-03-14T01:31:06Z_1741925227.tar.zst
⠴ Vulnerability DB                ━━━━━━━━━━━━━━━━━━━━  [62 MB / 66 MB]  
```
This means if you have a previous grype scan with a DB URL in it (added in #2529) you can quickly use that reference to import the DB:
```
$grype db import $(cat mygrype.json | jq '.descriptor.db.status.from')
✔ Vulnerability DB                [imported]  
```
The value in grype JSON documents has the checksum of the argument as a query parameter (`https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-03-14T01:31:06Z_1741925227.tar.zst?checksum …
=> Allow import DB from URL

cmd/grype/cli/options/database_search_os.go, cmd/grype/cli/options/database_search_os_test.go, grype/db/v6/affected_package_store.go, grype/db/v6/affected_package_store_test.go, grype/presenter/table/__snapshots__/presenter_test.snap, grype/presenter/table/presenter.go, grype/presenter/table/presenter_test.go
Before this PR, it was not possible to specify a distro without exact version information, such as `--distro alpine:3.17`. There are cases users want to specify the distro but do not know the exact distro version to use. This PR relaxes the requirement to only use a single distro, allowing for specifying without a version, such as `--distro ubuntu` or only a major version like `--distro alpine:3`. The JSON output includes namespace information already, so a user can understand where matches came from, this PR also detects when multiple distros are present in the results and adds annotations to the table view to make this clear to users, e.g.:
```
NAME          INSTALLED  FIXED-IN              TYPE  VULNERABILITY   SEVERITY                            
...
ssl_client    1.34.1-r7 …
```
=> feat: specify distro without version

grype/db/v6/db.go, grype/db/v6/db_metadata_store_test.go, grype/db/v6/store.go, grype/db/v6/store_test.go
This PR fixes a panic due to attempting to close a nil pointer when a non-v6 database is used. Additionally, this improves the messaging to help users understand that they are using an incompatible database version. Example:
```
$ grype db import $(pwd)/v5vulnerability.db
✔ Vulnerability DB                [hydrating]  
[0007] ERROR unable to import vulnerability database: failed to hydrate database: not a v6 database: record not found
exit status 1
```
Fixes #2542
=> fix: panic and improve non-db-v6 error messaging

grype/vulnerability_matcher.go, grype/vulnerability_matcher_test.go
Today it is possible to panic and not recover within a matcher. This PR fixes this by recovering so that the UI can be shutdown gracefully and report the error. This is considered a fatal error still so no vulnerability results are returned in this case (when there is a panic, even when recovered).
=> Recover from panic within a matcher

internal/file/copy.go
Replace `os.ReadDir` with `afero.ReadDir` to consistently leverage afero's filesystem abstraction.
- **Only** replaced `os.ReadDir(src)` → `afero.ReadDir(fs, src)`.
- Minimal, no behavioral changes.
- Fully backward compatible.
=> Replace os.ReadDir with afero.ReadDir for consistency

cmd/grype/cli/commands/db_search_vuln.go, cmd/grype/cli/commands/db_search_vuln_test.go, internal/cvss/metrics.go, internal/cvss/metrics_test.go
Today there are raw `fmt.Sprintf("%v")` values without any stringer implemented (specifically when there is a CVSS as the primary severity entry). This PR fixes this behavior to show the string severity in this case.
=> Fix severity field in `db search vuln`

grype/match/matches.go, grype/matcher/internal/cpe.go, grype/matcher/internal/cpe_test.go, grype/matcher/internal/distro.go, grype/matcher/internal/only_vulnerable_versions.go
Searching with CPEs and PURLs with partial information should yield match results with version constraints not evaluated, however, today they are dropped entirely:
Before any code changes:
This change allows for empty versions, which will satisfy any version constraint; after the code changes:
Note this is subtly different than a version being explicitly `unknown`, which should not satisfy any version constraints.
- https://github.com/anchore/grype/pull/2590
=> Assume that empty versions should match on all possible versions

grype/db/v6/vulnerability_provider.go, grype/db/v6/vulnerability_provider_test.go
Fixes #2618 
Keeps #2608 fixed
Basically, update the logic so that we search by the Syft package type if it's non-blank and known, then by language if it's non-blank, then by "UnknownPkg" if the language is blank. #2608 was because we weren't searching by a non-blank language when the package type was "UnknownPkg" and #2618 was because we were searching by a blank language instead of "UnknownPkg".
I'll add some unit tests after I check with the team that this approach makes sense.
=> fix: only fallback to language if language is non-blank

.github/workflows/release.yaml
The release quality gate step polls to make sure the commit to be released has a green CI run. However if a PR is merged immediately before the release job is run, this step often times out. Raise the timeout to 20 minutes, which covers the time taken by recent CI runs.
Additionally, include the "Quality tests" step from validations.yaml in the tests to block on. It should always have been included.
=> chore: improve release quality gate

grype/pkg/purl_provider.go, grype/pkg/purl_provider_test.go
not sure what i am doing. but this seems to fix #2580
=> fix:  use namespace with name when purl is ecosystem golang in purl decoder

README.md, cmd/grype/cli/cli.go, cmd/grype/cli/commands/root.go, cmd/grype/cli/options/grype.go, cmd/grype/cli/options/sort_by.go, go.mod, go.sum, grype/presenter/cyclonedx/test-fixtures/snapshot/TestCycloneDxPresenterDir.golden, grype/presenter/cyclonedx/test-fixtures/snapshot/TestCycloneDxPresenterImage.golden, grype/presenter/internal/test_helpers.go, grype/presenter/json/test-fixtures/snapshot/TestJsonDirsPresenter.golden, grype/presenter/json/test-fixtures/snapshot/TestJsonImgsPresenter.golden, grype/presenter/models/sort.go, grype/presenter/models/sort_test.go, grype/presenter/models/vulnerability.go, grype/presenter/models/vulnerability_metadata.go, grype/presenter/sarif/presenter_test.go, grype/presenter/sarif/test-fixtures/snapshot/TestSarifPresenter_directory.golden, grype/presenter/sarif/test-fixtures/snapshot/TestSarifPresenter_image.golden, grype/presenter/table/__snapshots__/presenter_test.snap, grype/presenter/table/presenter.go, grype/presenter/table/presenter_test.go, grype/vulnerability/metadata.go, grype/vulnerability/metadata_test.go
This adds a new `risk` metric to the grype results, allowing us to show prioritized vulnerability mathces in a way that helps users remediate the most "important" vulnerabilities first. 
The new `risk` metric is defined as `risk ~= threat * severity`, where:
- `threat` is the EPSS score for the CVE matched with (between 0-1), or if present on the KEV  list, then boosted by 5% (10% if the vulnerability is being used in ransomeware)
- `severity` is the average CVSS base score + string severity on the vulnerability record (scaled to between 0-1)
- the entire result is scaled to be a result from 0-100
**Grype results, regardless of the format, will be sorted by highest-risk-first by default**. Also the raw risk value will be added to the table and json output formats.
A new `--sort-by …
=> Add risk score to results and sort by risk by default

grype/version/constraint_expression.go, grype/version/constraint_expression_test.go, grype/version/pep440_constraint.go
If a given constraint unit cannot be parsed as its labeled type, try parsing it as a fuzzy version. In this way matching can be attempted even in the face of surprising upstream data.
See #2642 for a discussion of why. A companion grype-db PR will be up in a moment to write these range entries into the database as fuzzy entries.
The core issue here is how to handle GHSA entries whose version constraint is not a valid version for the language ecosystem that the affected package belongs to. The heuristic implemented in this PR helps with the Go and Python GHSAs that we are aware of, but doesn't help with the Ruby GHSAs. Follow #2646 for the Ruby-specific work needed here.
=> fix: fall back to fuzzy constraint units

grype/pkg/package.go, grype/pkg/package_test.go
Adjust the prefix check to allow removing an owned package if either version is a prefix of the other.
=> fix: adjust version prefix check when excluding overlapping packages

cmd/grype/cli/commands/root.go
The provider is supported, but was missing from the help text. I found out only after inspecting the source. I understand that matching with purl is more precise, but some applications cannot be represented as PURL.
=> minor: add CPE source to the help text

grype/db/v6/db.go, grype/db/v6/refs.go, grype/db/v6/store.go
This removes the unexported getDB() call from the v6 DB Reader interface and exports the method in the underlying implementation so that callers can type assert out the lower-level reader if they need.
=> Remove getDB() from the v6 DB reader

Dockerfile, Dockerfile.debug
An upstream issue with busy box was causing issues over in syft where users would see:
```
wget: TLS error from peer (alert code 40): handshake failure
wget: error getting response: Connection reset by peer
```
This could cause issues in ci pipelines where users needed the debug image of syft for running pre CI commands before the sbom functionality was invoked.
Similar bugs could be expected in grype given the same base images are in use here.
This PR moves grype forward to use the rolling tags for `latest` and `debug` images from distroless debian12. We also have upgraded from debian11
Here is a local demonstration of the fix. PR reviewers can pull down the branch and run `make snapshot` to build the docker images and test on their local:
```
[I] (base-image-updates)> docker run -it …
```
=> chore: update dockerfile base images to latest rolling tags

grype/db/v6/installation/curator.go, grype/db/v6/installation/curator_test.go
Previously, when GRYPE_DB_CACHE_DIR was set to a docker volume, the grype temp dir could be created under the /tmp volume in the container but the final destination be under the named volume, which caused os.Rename to fail with an invalid cross-volume link error. Now, ensure that the temporary and final DB location are on the same volume by creating the temp dir under GRYPE_DB_CACHE_DIR.
Fixes #2517
=> fix: ensure temp dir on same volume as final db dir

go.mod, go.sum, grype/pkg/package.go, grype/pkg/package_test.go, grype/pkg/purl_provider_test.go
This is a follow on to https://github.com/anchore/syft/pull/3922 where there will no longer be a `syftPkg.JavaArchive.PomProperties` to reliably read java group ID / artifact ID from on SBOM decode operations. Specifically, this can't be depended on in cases where we don't know if the data actually came from a `pom.properties` file. Instead this is done when creating a grype package when we detect the package represents a java package.
- https://github.com/anchore/syft/pull/3922 CI will fail until this is merged and incorporated here
=> Parse java group ID and artifact ID from PURL when missing

cmd/grype/cli/cli.go
This allows for API users to use the internal clio configuration as is without needed to reproduce it.
=> chore: expose setup of clio setup config

cmd/grype/cli/commands/db_search.go, cmd/grype/cli/commands/db_search_vuln.go
Today if you use `db search [vuln] ID -o json` and the ID yields no results, then you will see:
```
No results found
```
However, the correct output should be an empty array:
```
[]
```
This PR fixes this behavior.
=> Always show results with json output for `db search` commands

grype/matcher/apk/matcher_test.go, grype/matcher/internal/cpe.go, grype/matcher/internal/cpe_test.go, grype/pkg/upstream_package.go, grype/presenter/cyclonedx/test-fixtures/snapshot/TestCycloneDxPresenterDir.golden, grype/presenter/cyclonedx/test-fixtures/snapshot/TestCycloneDxPresenterImage.golden, grype/presenter/internal/test_helpers.go, grype/presenter/json/test-fixtures/snapshot/TestJsonDirsPresenter.golden, grype/presenter/json/test-fixtures/snapshot/TestJsonImgsPresenter.golden, grype/presenter/models/package.go, grype/presenter/template/test-fixtures/snapshot/TestPresenter_Present.golden
This PR fixes an issue with JSON output where CPE segments are not properly escaped in the same way Syft outputs escaped CPE segments.
=> fix: properly escape CPE segments

.github/workflows/codeql-analysis.yml, Taskfile.yaml
This runs in the fraction of the time and resources, but still getting the same paths reported as on the runs on main today. This restricts the scans to only cover the golang code.
=> Use shared workflow for CodeQL scans

.github/workflows/validations.yaml, cmd/grype/cli/commands/root.go, cmd/grype/cli/commands/root_test.go
Previously, grype would disregard default vex behavior in the presence of other ignore rules. Instead, append default vex ignore rules if any vex documents are used, even if other ignore rules exist.
Fixes #1836
=> fix: append vex ignore rules if vex doc is present

grype/db/v6/installation/curator.go, grype/db/v6/installation/curator_test.go, internal/schemaver/schema_ver.go, internal/schemaver/schema_ver_test.go
Grype client should hydrate the DB when there are new client features.
For example: if a v6.0.2 client downloads a v6.0.2 DB and hydrates it, then a newer client (v6.0.3) runs a scan then the client should hydrate the DB (assuming there is no v6.0.3 DB available to download for whatever reason).
New clients may depend on new columns existing in the DB, and hydrating will auto-migrate the tables to include these new columns (with empty values). This doesn't mean that the client will logically perform the correct behavior if the new feature does not gracefully degrade, but it does prevent against SQL-level errors about columns not existing. Note that this would still allow for older clients to use the DB hydrated by the new client.
=> fix: DB should hydrate for when the client has new features

.github/workflows/release.yaml
https://github.com/anchore/grype/pull/2759 will be fixing a bug but introducing false positives, which means release checks will not allow the release to continue. This adds a manual override to allow for the release (break glass in case of emergency).
=> Add ability to skip release checks feature for emergency releases

grype/matcher/internal/only_vulnerable_targets.go, grype/matcher/internal/only_vulnerable_targets_test.go
Normally, when matching CPEs with the target SW filled as a non-wild, Grype attempts to normalize the target SW field to a known package type, e.g. ".net" and "dotnet" both compare as "dotnet" at match time. However, this code dropped unknown target SW types, resulting in false negatives for target SW entries that did not correspond to a particular package type, e.g. "chromium". Therefore, if a target SW is not known to Grype, and not a wildcard, lowercase it and consider it for matching.
Fixes #2768
=> fix: preserve target sw when unknown

grype/presenter/table/__snapshots__/presenter_test.snap, grype/presenter/table/presenter.go
Today KEV annotations are displayed using characters that require powerline glyphs, which requires either a special font or special terminal support to render. In order to increase portability this replaces the "pill" pattern with a simple block equivalent:
Before:
After (with PR changes):
There isn't a reliable way to detect when there is support for rendering these glyphs, so for now it is simpler to not use them (we already gracefully degrade to showing alternative formats when there is no tty available, however, that does not help in this case).
=> Remove pill pattern from table output

grype/db/v5/distribution/test-fixtures/tls/generate-x509-cert-pair.sh
=> chore: remove disallowed characters from hostname before test fixture cert generation

.github/workflows/release.yaml
With https://github.com/anchore/grype/pull/2804 we updated our security around github actions using the zizmor linter to call out common pitfalls and misaligned files.
This PR reverts a small change in #2804 by setting `persist-credentials: true` for the release step of grype.
Here we are still following the outlined practice in the linter documentation:
https://docs.zizmor.sh/audits/#artipacked
> Unless needed for git operations, [actions/checkout](https://github.com/actions/checkout) should be used with persist-credentials: false. If the persisted credential is needed, it should be made explicit with persist-credentials: true.
We are being explicit with this change that we need `persist-crendentials: true` in this case
=> chore: revert credentials persistence for release

go.mod, go.sum, grype/presenter/models/source_test.go
A follow up to https://github.com/anchore/syft/pull/4077 and https://github.com/anchore/grype/pull/2821 to prevent issues like described in https://github.com/anchore/grype/issues/2819 from being released in grype when we add new sources in syft.
=> chore: add source completion testing

test/quality/.yardstick.yaml
Updates the label data and switches the bitnami spark image under test to a clone in the Anchore GHCR registry.
=> test: update quality gate labels and images

cmd/grype/cli/commands/db_search.go, cmd/grype/cli/commands/db_search_test.go, cmd/grype/cli/commands/internal/dbsearch/affected_packages.go, cmd/grype/cli/commands/internal/dbsearch/vulnerabilities.go
Otherwise, there will be rows that are apparently identical besides the fixed version, which makes the output hard to interpret. Include the channel at the end of the namespace looking string in the table output and on the OS object in the JSON output.
=> feat: include channel in grype db search output

grype/db/v6/data.go, grype/distro/distro_test.go, grype/distro/test-fixtures/os/raspbian/etc/os-release, grype/distro/type.go
Support matching packages from raspbian against the debian vulnerability data provider.
This will require a new db to be published by grype-db before the matching will work since it needs a new operating_system_specifier_override record in the db
=> feat[raspbian]: support vulnerability matching for raspbian

grype/version/fuzzy_constraint.go, grype/version/fuzzy_constraint_test.go
This makes version numbers that mix alphabetic and numeric components, like 4.2.8p14 and 4.2.8p2 compare correctly, e.g. 4.2.8p2 < 4.2.8p14 because 2 < 14. Previously, they would compare lexicogrpahically, occasionally resulting in a false positive or false negative.
A motivating real case:
``` sh
$ grype -q "cpe:2.3:a:*:ntp:4.2.8p15:*:*:*:*:*:*:*" | rg -e NAME -e CVE-2016-7434
NAME  INSTALLED  FIXED IN          VULNERABILITY   SEVERITY  EPSS          RISK  
ntp   4.2.8p15   *4.2.8p9, 4.3.94  CVE-2016-7434   High      61.2% (98th)  41.0 
$ go run ./cmd/grype -q "cpe:2.3:a:*:ntp:4.2.8p15:*:*:*:*:*:*:*" | rg -e NAME -e CVE-2016-7434
NAME  INSTALLED  VULNERABILITY   SEVERITY  EPSS         RISK  
$ grype db search --provider nvd --vuln CVE-2016-7434
VULNERABILITY  PACKAGE …
```
=> feat: detect patch numbers in fuzzy version comparison

README.md, cmd/grype/cli/commands/root.go, cmd/grype/cli/options/grype.go, grype/presenter/internal/test_helpers.go, grype/presenter/json/presenter_test.go, grype/presenter/models/descriptor.go, grype/presenter/models/document.go, grype/presenter/models/document_test.go, grype/presenter/table/presenter_test.go
Allows for configuring whether or not to include a timestamp in the final output via config option or env variable. Default is true. Resolves #522
=> Configurable timestamp

grype/db/v6/vulnerability.go, grype/db/v6/vulnerability_test.go, grype/presenter/models/vulnerability.go, grype/presenter/models/vulnerability_test.go, grype/vulnerability/fix.go
Though the DB search commands and the DB schema all have fix available information, and the JSON model had a place for the information, they were not wired up. This PR fixes two things:
- wires up the available date information from the DB
- pairs up expressing which fix date corresponds with which version without breaking the current JSON output
=> Present fix available version in grype JSON output

grype/pkg/rpm_metadata.go
Adding `cyclonedx` annotations for `RpmMetadata`. This allows for sboms in format `cyclonedx` to populate correctly the `RpmMetadata`.
=> fix: Add cyclonedx to RpmMetadata
